### ISSUE TITLE
Ability to Use Multiple Classifications in Ranked Report

### ISSUE THREAD

**Issue by framingeinstein** [randyzwitch/RSiteCatalyst#108]
I am trying to use more than one classification in a report request.  I do not see a way to do this though. Let me know if I am correct that the code base does not handle this or if I should be going about this problem differently.

Here is the code as RSiteCatalyst will accept:

```
#elements to breakdown by
elements <- c("trackingcode", "trackingcode")
#classifications to apply
classification <- "Campaign Type"
#applied to first element
selected <- c("Tactical", "LifeCycle", "Loyalty", "Remarketing")
segment.id <- "53c059aee4b07cd3c4332163"
report.data <- QueueRanked(reportsuite.id, last_week[1], last_week[2], metrics$id, elements, segment.id = segment.id, classification=classification, selected=selected)

```

I have modified to code to allow me to do the following here http://github.com/framingeinstein/RSiteCatalyst 

```

#elements to breakdown by
elements <- c("trackingcode", "trackingcode")
#classifications to apply,  applied to the elements in order
classification <- c("Campaign Type", "Campaign Name")
#applied to first element only
selected <- c("Tactical", "LifeCycle", "Loyalty", "Remarketing")
segment.id <- "53c059aee4b07cd3c4332163"
report.data <- QueueRanked(reportsuite.id, last_week[1], last_week[2], metrics$id, elements, segment.id = segment.id, classification=classification, selected=selected)
```

This works and produces the appropriate results from the API.  Here is the request and response:
https://gist.github.com/framingeinstein/23ae8cb77dd570ade771

The BuildInnerBreakdownsRecursively method does not seem to handle the result though.  The method looks like it should handle it but it is a little hard for me to decipher.  I was proceeding down the road to update this method but wanted to see I am just missing something or that can be achieved more efficiently first. 

Thanks,
Jason

**Comment by sreekrishnadutta** [comment]
I am trying to filter out visits from campaigns. I do not have SAINT classifications in place, and for now I am only trying to filter campaigns by the names. For example, "burnout_sale_ph" and "yp001215keycar" are two campaigns. I want to filter out campaigns in a QueueRanked report in an API call. I am able to do this using `search = c("_", "yp"), search.type = "or"`. Is there a way to exclude these? I tried `search.type="not"` but it did not work. Thank you!
