### ISSUE TITLE
Build Data Warehouse API functionality

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#116]
Up for grabs for anyone who has the desire to contribute

https://marketing.adobe.com/developer/documentation/data-warehouse/c-data-warehouse-api

**Comment by jgooly** [comment]
Very interested in the data warehouse package as well!

**Comment by WillemPaling** [comment]
Looks like there's been a pretty major update here:
https://marketing.adobe.com/developer/documentation/data-warehouse/r-report-2

**Comment by randyzwitch** [comment]
Nice find! One of the major reasons I hadn't built the package yet was because it was still on the 1.3 endpoint; I figured there was no way that was going to keep on.

So I guess I'll re-open this, see if there are any takers ;)

**Comment by WillemPaling** [comment]
There's also some upcoming Analytics for Target reporting that I'm on the beta on. It'll mean a new Queue and Parse function for a new report type. I'll try to build this one out in the next month or so.

Data Warehouse seems like a bigger beast - I don't think I'll have time for that in the near future.

**Comment by randyzwitch** [comment]
That's ok, I'll probably do it at some point. I'm still holding out hope that a magic PR will come from out of nowhere though :)

**Comment by randyzwitch** [comment]
@WillemPaling, we might need to start prefixing functions, if we're going to add Target and DW into this same package. Just something to think about

**Comment by johnbracey25** [comment]
Would be VERY interested in a DW API package for R if you are still considering it

**Comment by randyzwitch** [comment]
Closing again. Re-made AdobeDW a public package again, though its functionality is non-existant. Hopefully I can work on it before the end of the year.
