### ISSUE TITLE
Error when running a series of queries using apply

### ISSUE THREAD

**Issue by jeremiahpslewis** [randyzwitch/RSiteCatalyst#117]
The following appears about 50% of the time, seemingly randomly, when making calls to the API...

```
  ERROR: Bad Request  -  The specified created timestamp ('2014-12-02T11:59:30Z') has expired or is in the future ..
```

**Comment by johnbracey25** [comment]
I get the same issue when running a queueTrended report.  Funny thing is I ran the exact same report yesterday with no issue:

Error in SubmitJsonQueueReport(toJSON(report.description), interval.seconds = interval.seconds,  : 
  ERROR: the API validated the report, but did not return a report ID

**Comment by randyzwitch** [comment]
Could you be more specific, in terms of what version of RSiteCatalyst you are using, the function call you used, operating system, what time zone you're in, whether you were using an apply function, etc.

**Comment by johnbracey25** [comment]
Yes of course :).  

1.  Just downloaded the most recent version this morning from CRAN
2.  I am using a Queue Ranked Report (see below)
3. No apply function

A funny note...  When I mess with the date range it works sometimes.  Smaller ranges seem to work.  

Query1 <- QueueRanked("xxx", "2015-01-01", "2015-05-31", c("metric1", "metric2"), 
                               c("element1","element2", "element3"), selected = c("x","y"), 
                               segment.id = "xyz",segment.inline = "",
                               classification = character(0), data.current = FALSE, expedite = FALSE, 
                               interval.seconds = 5, max.attempts = 120)

**Comment by randyzwitch** [comment]
Not sure what to suggest if it sometimes works and sometimes doesn't, especially if it's predicated based on changing the dates

**Comment by sushant204** [comment]
Even i am facing this issue

**Error in ApiRequest(body = report.description, func.name = "Report.Validate") : 
  ERROR: Bad Request  -  The specified created timestamp ('2018-03-02T14:36:41Z') has expired or is in the future**

how should i resolve this?
