### ISSUE TITLE
Queueranked errror when more than 1 element in the query 

### ISSUE THREAD

**Issue by egorvodkin** [randyzwitch/RSiteCatalyst#122]
Hi colleagues!
I use 1.4.2 version of RSiteCatalyst and faced the following issue: while trying to get data using QueueRanked with two elements selected I get the error

```
> prodcsat <- QueueRanked(reportsuiteid, start_date, end_date, metrics=c('pageviews'), elements=c('prop8','prop20'), top = '1', start = '1')
[1] "Requesting URL attempt #1"
[1] "Requesting URL attempt #2"
[1] "Requesting URL attempt #3"
[1] "Received ranked report."
Error in if (nchar(elements[i, ]$classification) > 0 && !is.na(elements[i,  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In is.na(elements[i, ]$classification) :
  is.na() applied to non-(list or vector) of type 'NULL'
```

When I try to get report with a single element everything works OK, but I get an extra empty column named "url". Maybe this is causing the issue on JSON parsing.

**Comment by randyzwitch** [comment]
I'm going to close this out, it should be fixed in the master branch. 

```R
library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="master")
```

I'll likely push a version to CRAN in the next week or two, if you'd prefer to wait and not mess around with devtools.

**Comment by simonbalder** [comment]
I have a similar issue with the latest version. Also, I have two different machines running the same query. One of them is giving the error, the other one is not.

The command library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="version_1_4_1")

Also resulted in a 404 error.

query:

data <- QueueTrended("reportsuite,
                        startdate,
                        enddate,
                        c("visits","pageviews"),
                        elements = c("product","device"),
                        classification = "productcategory",
                        segment.id = "segment",
                        date.granularity = "day",
                        top = c("100","100"))
[1] "Requesting URL attempt #1"
[1] "Requesting URL attempt #2"
[1] "Requesting URL attempt #3"
[1] "Requesting URL attempt #4"
[1] "Requesting URL attempt #5"
[1] "Requesting URL attempt #6"
[1] "Requesting URL attempt #7"
[1] "Requesting URL attempt #8"
[1] "Requesting URL attempt #9"
[1] "Requesting URL attempt #10"
[1] "Requesting URL attempt #11"
[1] "Requesting URL attempt #12"
[1] "Requesting URL attempt #13"
[1] "Received trended report."
Error in if (!is.null(elements[i, ]$classification) && nchar(elements[i,  : 
  missing value where TRUE/FALSE needed

**Comment by randyzwitch** [comment]
Thanks @simonbalder for reporting this. Can you make a new issue? GitHub's interface makes it difficult to track comments on closed issues.
