### ISSUE TITLE
Pulling aggregate data that spans >1 year

### ISSUE THREAD

**Issue by Gitzman** [randyzwitch/RSiteCatalyst#127]
Hi Team,

Currently, the QueueOvertime features only allows for date granularity spanning 1 hour: 1 year.  The week granularity only shows for Omniture week.  I am trying to pull weekly aggregated data based on a fiscal week that is different from Omniture week.  I have created the appropriate set of dates and written a for loop to cycle through the dates and pull a query with each range.  I use year aggregation which is the longest range possible.  The issue is when my code reaches a Fiscal Week that spans the new year, the returned df has 2 entries, one for each part of the year that the week spanned.  I am hoping to get weekly unique visitors, so this is an issue for my data.  There is no way for me to pull this data from like QueueRanked, because there is no element associated with my request.  Is it possible for future releases to offer a "None" date granularity?  Can you think of anything else I could do to hack this data?  Let me know.  Thanks a lot.

**Comment by randyzwitch** [comment]
The R package builder messed it up it the documentation, but you can actually pass `""` (two double quotes, no spaces) to the API and it will return one row as a summary.

Note for everything else, changing the Omniture week or anything else isn't something I can modify, as all the package does is submit JSON to the API and parse the returned JSON from the API. No calculations are actually done.

**Comment by Gitzman** [comment]
Ok I figured the second part, but I am still very happy that I reached out and asked because there was a solution.  As always, thank you very much!
