### ISSUE TITLE
SCAuth couldn't connect to host on Windows 7 and RStudio 3.1.2, is it just me?

### ISSUE THREAD

**Issue by agerome-tes** [randyzwitch/RSiteCatalyst#128]
Hi Randy et al,

Is anybody else having the error below when calling SCAuth?:

Error in function (type, msg, asError = TRUE)  : couldn't connect to host

I'm on Windows 7 32 bit and I am using version 3.1.2 of RStudio.

Cheers,

Alban

**Comment by randyzwitch** [comment]
Have you ever been able to use this setup to connect to the API or is this your first time using the package?

**Comment by agerome-tes** [comment]
Hi Randy, I have been using the package for several weeks and then we have moved floors. I have checked with our network and firewall provider but we have not found anything that could explain why I can no longer connect now.

**Comment by randyzwitch** [comment]
Ok, just making sure you had all your credentials done properly :)

I just ran the full test suite from inside my RStudio project in OSX and it ran without issue, so I'm not sure what to tell you. Unfortunately, I don't have access to a Windows machine to test, nor a 32-bit one at that. There is no operating-system specific code for RSiteCatalyst itself, but that's not to say that RCurl/httr or stringr, plyr or anything else doesn't have a bug.

Sorry I couldn't be more help, good luck!

**Comment by randyzwitch** [comment]
Were you able to get this straightened out? @agerome-tes

**Comment by agerome-tes** [comment]
Hi Randy, no I have not found a solution. I'll try RSiteCatalyst at home and see if it's working. I am also having issues when trying to install the xlsx and XML packages, the files download partially and then the install fails. According to the firewall engineer the issue lies with the CRAN server but I was able to download and install these 2 packages on my home laptop just fine. I would not be surprised if RSiteCatalyst installs on my home laptop fine and lets me connect to our Adobe Analytics API account.

**Comment by agerome-tes** [comment]
Hi Randy, I have moved floors and a colleague who has stayed on the same floor as the one I was on is still able to install, load RSiteCatalyst and run the SCAuth function. So it definitely has nothing to do with your package but how the floor I am on now is connected to the internet.

**Comment by randyzwitch** [comment]
Great, glad you've narrowed down the issue. Hopefully you can get it fixed soon.
