### ISSUE TITLE
Multiple Elements in Report Bug

### ISSUE THREAD

**Issue by poochmonster** [randyzwitch/RSiteCatalyst#134]
As mentioned at the bottom of Issue #68, I will sometimes get the following error when working with Trended Reports with multiple elements:

Error in names(counts.df) <- metrics : 
  'names' attribute [1] must be the same length as the vector [0]

My hunch + lightweight testing leads me to think it's triggered when the combination of elements from one date range do not match those on another date range e.g in a browser report one day there were Mozilla visits and the next day there were none.

I also triggered the above error by picking a search keyword that didn't exist and presumably should have returned null or something.

**Comment by randyzwitch** [comment]
This is a difficult bug to squash. Would you be willing to submit the raw JSON response, so that I can understand what structure is causing a failure?

**Comment by poochmonster** [comment]
Sure, I've prepared a json file, but I guess you can only upload images to this thread. Any suggestions about how to best submit it?

**Comment by randyzwitch** [comment]
You can email it to me at rzwitch+rsitecatalyst@gmail.com

**Comment by randyzwitch** [comment]
I'm going to close this...this is almost certain to be the same issue as #135, so might as well make one meta issue instead of updating in two places.
