### ISSUE TITLE
GetSegments() unable to retrieve segments

### ISSUE THREAD

**Issue by wingyeelee** [randyzwitch/RSiteCatalyst#136]
Hello Randy,
I am new to RSiteCatalyst and it is really useful and easy to use.  Thank you for creating it.
I have tried to use the GetSegments() but somehow it keeps returning "No Segments Defined For This Report Suite" even there are segments.
What could be the issue?  Thank you.
Kind regards,
Wing

**Comment by engti** [comment]
Not Randy -  but please check in your segment manager if you have segments attached to this particular RSID you queried for. Otherwise, just create a segment specifically within this RSID and make a query. In omniture web interface you can use segments across report suites, but this query only pulls segments attached to a particular report suite. This anyway is my suspicion.

**Comment by randyzwitch** [comment]
Thanks @engti, I don't think there's anything else I can add here. Going to close this since it's not a package issue (i.e. the API is returning a response to you, just not what you expect), but please feel free to comment here if it continues to not work for you

**Comment by wingyeelee** [comment]
Thank you @engti and @randyzwitch.
I have tried creating a new segment and not shared it.  Unfortunately still getting the same results.  Would it matter that I am using the latest Analytics version?

**Comment by engti** [comment]
It should not make a difference. Please try the following code:

```
#Get Report Suites
report_suites <- GetReportSuites()

#Get Segments
segments <- GetSegments(report_suites$rsid)
```
Then try to see where your segments are located.

**Comment by wingyeelee** [comment]
Thank you @engti 
I have just tried the two lines.  The first line returns multiple rows, but the second returns [1] "No Segments Defined For This Report Suite"

**Comment by engti** [comment]
The only other thing I can think of is if the user id you're using for the API call is different from the user ID you're using for the Web Interface login. If that is the case when you share the segments from the web interface with the API user then you should see the segments come up.

**Comment by wingyeelee** [comment]
@engti - Thank you for this idea!  Will check this out.
