### ISSUE TITLE
QueueTrended  Arguments : top not returning the number of rows

### ISSUE THREAD

**Issue by woshitom** [randyzwitch/RSiteCatalyst#137]
Hello,

I am trying to use the QueueTrended to select the top 2 rows . ( My final objective is to loop using start and top to retrieve a massive amount of data) .

The top arguments  works when I have  one elements by giving me only the first two rows.

    date.from <- "2015-06-20"
    date.to <- "2015-06-20"
    reportsuite.id <- "***"
    metrics <- c("pageviews")
    elements <- c("evar11")
    start <- 1

    report.data <- QueueTrended(reportsuite.id, date.from, date.to, top = "2", metrics, elements ,     date.granularity = "year" ,  start=start )

But when i put two elements, the top arguments returns all the lines for the distinct first two evar11 ( which is my first element). 
To be more precise , If i want to split by customer and by product i will have all the lines of the first two customers instead of having only two lines

Same code as above but replacing elements by this 

    elements <- c("evar11","prop28")

Since top is made to return the number of rows isn't there a problem or something that i don't understand 

Thanks ,

**Comment by engti** [comment]
FAIK, You can only specify the number of results to return for the first element. There doesn't seem to be a way to control the number of breakdowns available for the second element specified.

**Comment by randyzwitch** [comment]
This is correct, currently the package only applies top to the first element. There's no reason a second parameter couldn't be added; however, this would need to be done in a backwards compatible way for those expecting the current behavior.

Ultimately, the original design goal of this package was to make it easy to get more analytics data than the Adobe interface allowed, not really fine grained control (since R already gives a way to further process the results).

I'm open to anyone who wants to take a shot modifying the package to add additional functionality via pull requests, so if this is important to you, look in the code for hard-coded values of 50000, which is the API return limit. Make that an argument into the function and your functionality will be implemented.

**Comment by WillemPaling** [comment]
I think the best approach would be to make it an optional property of an element.

So elements can be c("evar1","evar2"), or it could be something like c("evar1"=c("top"=10,"element"="evar1"),"evar2"=c("top"=100,"element"="evar3")).

If top is specified alone, it can apply to the first element, and if it is specified with the element, then it will override it.

I did look at this originally, but it made the params really awkward.

@woshitom the other alternative would be to call JSONQueueReport directly.
If you just write a report definition as a JSON string, RSiteCatalyst will parse it even if you have 50000 breakdowns on every element.

**Comment by randyzwitch** [comment]
That seems really awkward to attach the "top" to the element itself. Seems like it would be better to just test for the length/class of the vector. The current behavior is a string/int, so if we tested for a character vector of length 2, then we could handle it that way.

**Comment by randyzwitch** [comment]
I finally got around to evaluating this...so, you've found a bug/oversight. `top` plain just isn't implemented for more than one element. That itself is an easy fix I suppose.

@woshitom, is your use case that you want to limit the first element using `top`, then get all of the rows of the second element, or are you looking for control over both? If I were to fix the error identified above, I think the second element would still only return 10 rows per unique first element, unless I made additional modifications.

**Comment by randyzwitch** [comment]
@woshitom @WillemPaling @engti Could any/all of you test this fix on the `qt branch` before I merge it in? I literally copy-pasted the code from `QueueRanked` into `QueueTrended`, as it was 95% similar. This changed passed all the existing unit tests, but it feels too easy/too much like a hack for me to be comfortable.

Just run any existing `QueueTrended` calls, make sure they still work. Also, make sure using the `top` parameter actually gives different results when using 2 or more elements.

Thanks!

```R
library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="qt")
```

**Comment by engti** [comment]
@randyzwitch a bit busy today. But I'll surely be able to test it tomorrow.

-R

**Comment by WillemPaling** [comment]
Well...what do you know. I actually need this functionality today.
I'll test now.

**Comment by WillemPaling** [comment]
I seem to be testing things that cause timeouts. I'll try some different element combos instead.

**Comment by randyzwitch** [comment]
I'm considering this one fixed and will merge into master. If anyone finds any issues, file a new issue or comment here.
