### ISSUE TITLE
top gets ignored when you use segment.id in Queue* calls

### ISSUE THREAD

**Issue by tfindlay-au** [randyzwitch/RSiteCatalyst#141]
This could just be me, but if I use a segment.id then the top parameter gets ignored.

myResults<-QueueRanked(
    reportsuite.id=my.rsid
    ,date.from=my.dates[1]
    ,date.to=my.dates[2]
    ,metrics=c('pageviews')
    ,elements=c('prop1')
    ,selected=c('mySite')
    ,segment.id=c('551cbe9de4b060c76032878d')
    ,top=5
  )

This example returns 20 rows, if I remove the segment.id then I get 5 as expected.
If I use segment.inline I also get 5 as expected.

**Comment by randyzwitch** [comment]
To be honest, I'm surprised this works at all. I would think this would be undefined behavior; either `selected` or `top` should be used, but not both? If you only select a single value `c(`mySite)`, shouldn't that only return one row anyway?

I'll take a look at why it's `segment` that causes this, but I'm not sure this isn't just an undefined behavior from the API.

**Comment by tfindlay-au** [comment]
Thanks Randy, I'm happy to test and suggestions you might have. The reason we use the segment if to filter the results by elements other than the first in the element list.

**Comment by randyzwitch** [comment]
The more I think about this, I don't think there's anything I can/should do about this. At its most reductionist, RSiteCatalyst just submits JSON and then parses the result. Given that you get a result at all, that means the Adobe Analytics API accepts the combination of arguments as valid, and the parser just converts the result from JSON to a data frame.

Which is a long way of me saying, I'm going to leave this open for now but mark it as wontfix; anything I did to remedy this would be adding logic in between the API and the package that I don't want to maintain.

**Comment by tfindlay-au** [comment]
Thanks Randy,

I understand RSiteCatalyst is simply a wrapper for the API and agree with you about performing any DML which could be a never ending story.

I mainly wanted to raise awareness of the problem in case others came across it.

We love your package, and appreciate all the work you have put into it. Many thanks for sharing it with the world.

**Comment by randyzwitch** [comment]
Thank for the feedback @tfindlay-au, glad you are finding the package useful!
