### ISSUE TITLE
specify own endpoint url?

### ISSUE THREAD

**Issue by smaettig** [randyzwitch/RSiteCatalyst#142]
when authenticating using SCAuth I somehow don't get automatically forwarded to the correct data center where the report suite is lying. Would it be possible to implement a functionality to specify your favorite endpoint URL?

**Comment by randyzwitch** [comment]
Thanks. This shouldn't take too long to implement.

**Comment by randyzwitch** [comment]
@smaettig, can you try the fix I just pushed for this with the `endpoint` argument in SCAuth? You'll need to specify the full url such as `https://api.omniture.com/admin/1.4/rest/`

```R
library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="version_1_4_5")

library(RSiteCatalyst)
```

**Comment by smaettig** [comment]
Hi Randy,
Authentication seems to work when I add endpoint = "
https://api3.omniture.com/admin/1.4/rest" to SCAuth
and I am successfully getting e.g. the report suites via GetReportSuites().

However, as soon as I am calling a function where I need to define a report
suite IDl (for example GetElements(rsid)), I now always get a
"ERROR: Bad Request  -  reportSuiteID is required" even though I have
defined the desired ID.

Do I need to now add something additional to the reportSuiteID?

Thanks!
Stefan



On 10 August 2015 at 19:54, Randy Zwitch <notifications@github.com> wrote:

> @smaettig <https://github.com/smaettig>, can you try the fix I just
> pushed for this with the endpoint argument in SCAuth? You'll need to
> specify the full url such as https://api.omniture.com/admin/1.4/rest/
>
> library(devtools)
> install_github("randyzwitch/RSiteCatalyst", ref="version_1_4_5")
>
> library(RSiteCatalyst)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/randyzwitch/RSiteCatalyst/issues/142#issuecomment-129548854>
> .
>



-- 
Dr. Stefan Mättig, Data Scientist

stefan.maettig@sinnerschrader.com
T +49 40 398855 141

SinnerSchrader Deutschland GmbH | SinnerSchrader Group
Völckersstraße 38, 22765 Hamburg, Germany

Amtsgericht Hamburg HRB-Nr. 63663
Geschäftsführer: Matthias Schrader (Sprecher),
Jürgen Alker, Dr. Axel Averdung, Holger Blank,
Thomas Dyckhoff, Dr. Lars Finke, Martin Gassner

Büros: Hamburg, Frankfurt a. M., München, Prag

http://www.sinnerschrader.com | NEXT AGENCY

**Comment by randyzwitch** [comment]
There shouldn't have been any modifications to your code, as I only modified the `SCAuth` function.

When you use the API explorer with your company name, what do you get back?
https://marketing.adobe.com/developer/api-explorer#Company.GetEndpoint

**Comment by smaettig** [comment]
Hello Randy,
for some reason it also works in my R-Script now, maybe some connection was
down this morning when I tried first.
So please ignore my previous question and thanks again for adding the
option!!
Best regards,
Stefan

On 11 August 2015 at 15:05, Randy Zwitch <notifications@github.com> wrote:

> There shouldn't have been any modifications to your code, as I only
> modified the SCAuth function.
>
> When you use the API explorer with your company name, what do you get back?
> https://marketing.adobe.com/developer/api-explorer#Company.GetEndpoint
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/randyzwitch/RSiteCatalyst/issues/142#issuecomment-129864602>
> .
>



-- 
Dr. Stefan Mättig, Data Scientist

stefan.maettig@sinnerschrader.com
T +49 40 398855 141

SinnerSchrader Deutschland GmbH | SinnerSchrader Group
Völckersstraße 38, 22765 Hamburg, Germany

Amtsgericht Hamburg HRB-Nr. 63663
Geschäftsführer: Matthias Schrader (Sprecher),
Jürgen Alker, Dr. Axel Averdung, Holger Blank,
Thomas Dyckhoff, Dr. Lars Finke, Martin Gassner

Büros: Hamburg, Frankfurt a. M., München, Prag

http://www.sinnerschrader.com | NEXT AGENCY

**Comment by randyzwitch** [comment]
Awesome, glad to hear it! You can keep using this development version for now, and I'll submit a new version to CRAN in a few weeks so that you can have a "production-quality" release to use.
