### ISSUE TITLE
QueueRanked.R line 108 top-n for second element

### ISSUE THREAD

**Issue by tfindlay-au** [randyzwitch/RSiteCatalyst#146]
Hi,

Would you consider reviewing this to allow the 50000 limit to be overridden ?

If you possibly made "top" accept a vector. If one value supplied apply to first element, if 2 apply to second etc.

Our use case is one where we may want top 10 pages by a selected list of authors, the limit of 50000 means we get every article for each author which is a bit annoying.

**Comment by randyzwitch** [comment]
I took a look at your fork, it seems correct for both adding the `validate` parameter and for the `top` enhancement. Thanks for helping out!

Can you add the validate parameter to the other `Queue*` functions as well, then submit a pull request? That way, I can run the tests under my account and make sure that everything works correctly.

**Comment by tfindlay-au** [comment]
?Hi Randy,


I just had a hack at both as it serves our purpose. I've made a few other changes per:

  *   ?QueueTrended: Added Top + validate
  *   QueueSummary: Added validate, no top parameter for this function as its not appropriate
  *   QueuePathin: Added validate,  no change to top parameter as its a single element function
  *   QueueOvertime: Added validate, no top parameter
  *   QueueFallout: Added validate, no top parameter

I did some quick tests here and most of these seemed to work, but please test properly, hope the changes help.

Tim.


________________________________
