### ISSUE TITLE
SubmitJsonQueueReport.R: Line 42 could be a problem... 

### ISSUE THREAD

**Issue by tfindlay-au** [randyzwitch/RSiteCatalyst#149]
We observed a problem today with:
ERROR: the API validated the report, but did not return a report ID

The seems to be consistent for all our users. On inspection, it appears we DO get a report Id, but its just not an integer. eg:
{"reportID":"81905958"}

So maybe you could test casting it to an integer ? or something.

I raised a ticket with Adobe, but no response yet to confirm Adobe have changed it.

**Comment by randyzwitch** [comment]
Things work fine for all of the tests I have written. Not sure what to tell you.

**Comment by tfindlay-au** [comment]
Thanks Randy,

This could be an isolated problem, or even a transient one. If it doesn't affect anyone else, then leave it be and close the issue.

**Comment by WillemPaling** [comment]
I've just got the same problem. I'm updating my repo and I'll try to work out if it something that can be fixed in RSiteCatalyst.

**Comment by randyzwitch** [comment]
Scary thought that their API might not be deterministic in its results

**Comment by WillemPaling** [comment]
Casting it to an integer works. Adobe sometimes return it as a string, but in 99% of cases, return it as an integer.

  #If response returns an error, return error message. Else, continue with capturing report ID
  if(!is.na(as.numeric(response$reportID))) {
    stop("ERROR: the API validated the report, but did not return a report ID")
  } else {
    report.id <- response$reportID
  }

**Comment by tfindlay-au** [comment]
I just used:
  reportID<-as.numeric( response$reportID ) 
  if(!is.numeric( reportID )) {

**Comment by WillemPaling** [comment]
Like this?

#If response returns an error, return error message. Else, continue with capturing report ID
report.id <- as.numeric(response$reportID)
if(!is.numeric(response$reportID)) {
stop("ERROR: the API validated the report, but did not return a report ID")
}

**Comment by WillemPaling** [comment]
I'll make the update and submit a PR.

**Comment by tfindlay-au** [comment]
Yep, I'm not sure which is better, but you've got the idea.

As pointed out, its only an intermittent thing, sometimes you get a numeric, sometimes not.

I wondered if it might have something to do with the recent Sept update from Adobe ?

**Comment by randyzwitch** [comment]
Fixed with 1.4.6
