### ISSUE TITLE
Encoding 

### ISSUE THREAD

**Issue by ranelytics** [randyzwitch/RSiteCatalyst#151]
Hey Randy,

first of all thanks for this great package - It is *very helpful* for my day-to-day work!

After reading the package documentation thoroughly i encountered some kind of problem concerning german letters (mutated vowels like `Ä, Ö, Ü') in page names, search keywords e.g. if i try to fetch search keywords as described in one of your [blog posts](http://randyzwitch.com/rsitecatalyst-k-means-clustering/) some of the words are just hard to read. I want to emphasie that the query results are reasonable per se, they just dont seem to be formatted/encoded in the right way.

**Example:**
Instead of `Öffnungszeit`, which would be the correct term, the result of a ranked query is `Ã£ffnungszeit`. 

![umlaute_rsitecatalyst](https://cloud.githubusercontent.com/assets/14963783/12534331/4669834c-c254-11e5-8cc9-9a1c089b8ee9.png)

Maybe i am just not aware of some kind of language/encoding option in your package? Do you consider this a bug?

Thanks,
Lukas

**Comment by randyzwitch** [comment]
Hi Lukas, glad you are finding the package useful!

This is really just an oversight on my part, given my American-ness. This has never come up before, so I never implemented the encoding part of the API. :)

It shouldn't be too difficult to implement, it's just a lot of methods, so hopefully I can work on this in the upcoming week,

**Comment by randyzwitch** [comment]
@ranelytics, could you test this out for me? You can install the patched version using:

```R
install.packages("devtools")
library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="master")
```

There are two changes. First, just try to run your same code as you did before and see if your issues are fixed. There was an option for UTF-8 encoding, so I turned that on. If that doesn't work, `SCAuth` now has a keyword option for `locale`, and you can set Germany as your locale `de_DE`.

Thanks.

**Comment by ranelytics** [comment]
@randyzwitch, its working even without specifiying the new `locale` option but i added it nevertheless. you never know :)

again, **thanks** for this great package!

**Comment by randyzwitch** [comment]
Great, thanks for confirming! I'll send a new version to CRAN in the coming days.

You're quite welcome for the package, I hope you continue to find it useful.
