### ISSUE TITLE
Will you port this to Julia at some point?

### ISSUE THREAD

**Issue by alban-gerome** [randyzwitch/RSiteCatalyst#152]
Hi Randy,

So not an issue at all but just a quick question. I have been hearing a lot of good things about the Julia language, especially about how much faster it is than R and Python. I have notice that you code in Julia, I do not yet but are you considering implementing a similar package to RSiteCatalyst for the Julia language?

Thanks,

Alban

**Comment by randyzwitch** [comment]
Hey Alban, such a lovely idea. Unfortunately, I'm not sure it's really worth the effort for me to port it over, as the intersection of Julia users and Adobe Analytics API users has to be in the single digits. As it is, I'm not sure there are more than a few dozen RSiteCatalyst users :(

But I'll leave this open, because well, you never know. I do get bored some times and just start hammering out code!

**Comment by engti** [comment]
Hey Randy,

Thought I'd let you know that I use this extensively. And right now I'm training about 10 people at work to use R and a lot of our work is based on Adobe data, so you'd definitely be seeing a lot more usage of your package :)

Thank you so much for your work,

Robin

**Comment by randyzwitch** [comment]
Thanks for the note Robin, I'm glad you're getting so much value out of the package and are teaching others!

**Comment by WillemPaling** [comment]
I use it almost daily, and have it running jobs that power realtime dashboards running on TVs in our lobby. Do you get download stats from CRAN?

**Comment by randyzwitch** [comment]
Thanks Willem; I fear that I gave the impression that there was some sort
of pity in my original answer! I'm sure there are plenty of people using
the package, I just think it's a small fraction of Google Analytics, and
such a small fraction of all R users (and potential Julia users).

But now I need to know, so I'm downloading the CRAN RStudio logs :)

**Comment by randyzwitch** [comment]
I went and squatted on the name for Julia; if someone wants to do this before I get around to this (if ever), then they can have the name.

If anyone wants to follow progress (or lack thereof), then can follow this repository:

https://github.com/randyzwitch/AdobeAnalytics.jl
