### ISSUE TITLE
SCAuth Failed Error in curl::curl_fetch_memory(url, handle = handle) 

### ISSUE THREAD

**Issue by mathubhalan** [randyzwitch/RSiteCatalyst#153]
Hi Randy,
I'm trying to set up the environment to access the site catalyst data but failed in the first step, I have updated the proxy details in .Renviron with the below format and this proxy worked as expected in downloading the package but it doesn't work for the SCAuth, guide me on how to add the proxy for httr or curl..

options(internet.info = 0)
http_proxy="http://username:password@proxy"

**Comment by randyzwitch** [comment]
I have no idea how to solve this, as it's an issue with httr/RCurl, not RSiteCatalyst per se. And a Windows-specific issue at that.

**Comment by WillemPaling** [comment]
I've been through a few windows proxy battles with R.

Do you know what type of proxy you're dealing with? If it is an NTLM proxy,
I ended up having to install CNTLM locally to get around the issue. Other
proxies can be managed entirely in R.
