### ISSUE TITLE
Date From and Date To in Summary Report 

### ISSUE THREAD

**Issue by mathubhalan** [randyzwitch/RSiteCatalyst#158]
Hi Randy,
Thanks the RSitecatalyst package help me a lot by saving my time and effort spent on generating certain reports. I have a request, how easy was to add Date From and To in a summary report since the actual JSON support the date range.

Thanks & Regards
Mathu

**Comment by randyzwitch** [comment]
This is complete. You can use `devtools` to pull the master branch of RSiteCatalyst to use this new functionality, until I'm able to submit a new version to CRAN

**Comment by mathubhalan** [comment]
Thanks Randy thanks a ton for your help
