### ISSUE TITLE
Fix failing tests/Update dates

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#160]
The QueueRanked and QueueTrended parsers don't appear to be parsing some of the tests correctly, returning zero rows and columns instead of zero rows (potentially) with column headers. This isn't caused by #157, but was highlighted by it.

Fix the parsers to parse this correctly.

**Comment by randyzwitch** [comment]
Also, update dates in tests for newer time periods, perhaps even specify expected number of rows instead of just expecting a data frame

**Comment by Gitzman** [comment]
Do you think it would be possible/make sense to update the tests to run off the public account credentials adobe provided for the Real Time Dashboard to eliminate the dependency on you to run the tests?  Just wondering.

**Comment by randyzwitch** [comment]
What public account credentials?

**Comment by Gitzman** [comment]
![image](https://cloud.githubusercontent.com/assets/4806156/14049787/dc1301c0-f28d-11e5-9580-55a0836d3ed9.png)

I am not sure these will have non-realtime API permissions, but they might, and I imagine it would be useful.

**Comment by randyzwitch** [comment]
There isn't any data in the report suite.

**Comment by Gitzman** [comment]
![image](https://cloud.githubusercontent.com/assets/4806156/14050038/78857924-f28f-11e5-9be6-fd266b193399.png)

I'm seeing a bit of data.. Idk what's happening with the printing of "" right when I send the QueueOvertime function, but that's a different issue.

**Comment by randyzwitch** [comment]
It's fixed in master, you left a print debug statement in the code (which I removed).

If you run `GetSegments("rtd-example")` or `GetEvents("rtd-example")`, there's little implementation, certainly less than is needed for proper testing.

**Comment by Gitzman** [comment]
That's makes sense.  I figured it was worth investigate so you could get some help on the tests.  I guess it's not going to work out.

**Comment by randyzwitch** [comment]
Tests pass locally, not on Travis. Closing this now, but still trying to figure out what is going on https://github.com/hadley/testthat/issues/434
