### ISSUE TITLE
ERROR: element_top_invalid  -  The maximum number of top element values supported is 50000

### ISSUE THREAD

**Issue by snagahuiyan74** [randyzwitch/RSiteCatalyst#161]
Is there any way to modify the limit? Thanks.

Chris Lin

**Comment by randyzwitch** [comment]
No, that is the API limit set by Adobe. Use the `top` and `start` parameters to page over the results if you want to retrieve more than 50,000 results.

https://github.com/randyzwitch/RSiteCatalyst/blob/master/tests/testthat/test-queueranked.R#L21-L27
