### ISSUE TITLE
Q: How to use prop classification with QueueRanked fn?

### ISSUE THREAD

**Issue by sevcikra** [randyzwitch/RSiteCatalyst#162]
Following https://twitter.com/sevve/status/715150437809266688 I'd like to know how to use QueueRanked fn to pull out data broken down by a prop classification column:

`QueueRanked(reportsuite.id, date.from, date.to, metrics, elements, top = 0,
start = 0, selected = c(), search = c(), search.type = "or",
segment.id = "", segment.inline = "", classification = c(),
data.current = FALSE, expedite = FALSE, interval.seconds = 5,
max.attempts = 120, validate = TRUE)`

Best would be to be able to reference the classification field inside elements. I also see the classification fn parameter but I was not able to find any examples how to use it in the documentation.

Thanks

**Comment by randyzwitch** [comment]
Here's how to return a data frame where the "element" of the report is the SAINT classification, not the `element` specified in the argument. Basically, you have to reference the actual variable name as the `element`, then in `classification` put the grouping you actually want.

I'll take this as an opportunity to improve the documentation. Please let me know if this doesn't answer your question.

```R
temp <- QueueRanked(
                    reportsuite.id = your_report_suite, 
                    date.from = "2016-03-30", 
                    date.to = "2016-03-30",
                    metrics = "orders",
                    elements = "product",
                    classification = "Product Group"
                    )
```

**Comment by sevcikra** [comment]
- I have more than 1 element in the request and I see it automatically looks for classification of the 1st one. Can this be changed to point to 2nd, 3rd etc. element? 
- I only managed to receive 1 classification column per request. I expected this to work: classification = c("Position 1", "Position 2", "Position 3") but it seem it doesn't. Any idea why?

Thanks

**Comment by randyzwitch** [comment]
> "I have more than 1 element in the request and I see it automatically looks for classification of the 1st one. Can this be changed to point to 2nd, 3rd etc. element?"

Should one want to develop this functionality, I'm sure it's possible. It is not currently available.

> I only managed to receive 1 classification column per request. I expected this to work: classification = c("Position 1", "Position 2", "Position 3") but it seem it doesn't. Any idea why?

Because it isn't developed. But pull requests are always appreciated :)

**Comment by randyzwitch** [comment]
I think this might be the same as #207, so I'll close this one with the eye on fixing #207
