### ISSUE TITLE
Visitor based inline segmentation

### ISSUE THREAD

**Issue by blasp** [randyzwitch/RSiteCatalyst#164]
Hi Randy, is it possible to do a visitor based inline segmentation ?

Similar to this example in order to track users who have at some point in time viewed pet content.

mySegment<- list(container=list(type=unbox("visitors"),
rules=data.frame(
name=c("MobileDevices",'ViewPetContent'),
element=c("mobiledevicetype","page"),
operator=c("equals","contains"),
value=c("Mobile Phone","pet")
)))

thanks

**Comment by randyzwitch** [comment]
To be honest, I really don't know, as I don't use RSiteCatalyst to its full potential (i.e. I don't work in digital analytics any more).

Is this just an extension of #159 or something completely different? @WillemPaling, would you happen to know if this is possible?

**Comment by blasp** [comment]
Is similar but instead of using a hit segmentation to retrieve pages containing the word pet I want to use a visitor segmentation to retrieve the pages read by users who at any point in time read pet content.

**Comment by blasp** [comment]
Sorry this was an issue at my end. It is working fine.

thanks

**Comment by WillemPaling** [comment]
Good to know that resolved itself before I had a chance to look :)

**Comment by randyzwitch** [comment]
Always good when issues resolve themselves. Should probably build a convenience function at some point so people don't have to pass in such nasty code for a segment.
