### ISSUE TITLE
Is it possible to queue multiple reports?

### ISSUE THREAD

**Issue by shashispace** [randyzwitch/RSiteCatalyst#165]
I was wondering if it is possible to queue all the reports I want to get and then wait for all of them till ready? Adobe seems to advise that when you have a lot of reports to run.

Thanks guys! Not sure how to tag this as a question, not an issue.

**Comment by Gitzman** [comment]
This is feasible, but the solution I'd use is not related to RSiteCatalyst.  There are multiple R packages for parallel process that you could use, or the solution I'd use is to write a batch file that opens an instance of R for each query you'd like to run.  

Best of luck!

**Comment by randyzwitch** [comment]
> This is feasible, but the solution I'd use is not related to RSiteCatalyst. There are multiple R packages for parallel process that you could use, or the solution I'd use is to write a batch file that opens an instance of R for each query you'd like to run.

Yes and no. The question as I read it is more about concurrency; if you want to use RSiteCatalyst in a dashboard, the package is synchronous. You don't get a choice about whether you want to retrieve the answer, the submit and retrieve is a single function at the user API level.

To the original question, this could be implemented by a sufficiently motivated individual, but that individual isn't me. All you would need to do is add a keyword argument to bypass the retrieval of the report. `GetQueue()` will tell you what reports are available to pick up from the API, but some thought would need to be put into what the returned data structure would be.

For example, if you submit 10 reports, then pass the result of `GetQueue()` to some function, what would that single function return, a list of data frames? The choice that was made from the very beginning to call-receive from the API is the easier to think through; every function returns a data frame eventually.

**Comment by shashispace** [comment]
Thanks Randy - I've created a pull request: https://github.com/randyzwitch/RSiteCatalyst/pull/166

It has cut down my time from 2 hours to 14 minutes. And 9 of them still go into enqueueing the reports, where I think I could use something like foreach loop outside of RSiteCatalyst.
