### ISSUE TITLE
Q: How to pull click-through/campaign views metric?

### ISSUE THREAD

**Issue by datanerd10** [randyzwitch/RSiteCatalyst#167]
First off, thank you for the super helpful package @randyzwitch - it is a lifesaver! 

I want to pull campaign click-through metric or campaign views (as datawarehouse calls it) in QueueOvertime. 
(https://marketing.adobe.com/resources/help/en_US/reference/metrics_click-throughs.html)

When I look for this in GetSuccessEvents/GetMetrics, I am unable to find anything similar. Where can I find this metric?

**Comment by randyzwitch** [comment]
This is really an Adobe question, but not sure who or where you would ask.

Is `instances` an available metric?

**Comment by WillemPaling** [comment]
Try running GetMetrics(report suite id) and see if there's an appropriate metric.

I believe instances will show up there and is named 'instances'.

**Comment by datanerd10** [comment]
@WillemPaling and @randyzwitch instances is the right one. Thank you!
