### ISSUE TITLE
Classification Request Error

### ISSUE THREAD

**Issue by engti** [randyzwitch/RSiteCatalyst#172]
Hi All,

I wanted a report that gave me the _tracking code_ along with its classified values. To get that I tried the following:

`df1 <- QueueRanked(rsid,
                     date.from = "2016-01-01",
                     date.to = "2016-07-31",
                     metrics = c("entries"),
                     elements = c("trackingcode","trackingcode","trackingcode"),
                     classification = c("","Campaign Type","Channel")
                     )`

Which gave the following error:

`Error in if (!is.null(elements[i, ]$classification) && nchar(elements[i,  : 
  missing value where TRUE/FALSE needed`

Any idea if this is possible to do? And if I need to tinker with the package code, knowing where to tinker would be very helpful.

I can confirm that I can pull a request like this using the Adobe Report Builder.

Much Thanks.

**Comment by randyzwitch** [comment]
I think this might be the same as #207, so I'll close this one with the eye on fixing #207
