### ISSUE TITLE
Pre-use question: unique visitors de-duped? 

### ISSUE THREAD

**Issue by cdatwood** [randyzwitch/RSiteCatalyst#173]
Hello! I have a question about the package — when it pulls the uniquevisitor metric, do you know if the value is duped (like the total you would get at the bottom of an Omniture column representing the total minus duplicates), or if it just returns the individual non-de-duped values on whatever granularity you set? 

Thanks!

**Comment by randyzwitch** [comment]
uniquevisitors will only be correct at the row-level, i.e. whatever granularity you pick. If you want a de-duped value, you can either use no granularity  or use the `QueueSummary` method (the latter likely being what Adobe uses).

**Comment by cdatwood** [comment]
Fantastic! Thank you so much for that. Something to go test out.
