### ISSUE TITLE
segment.id and segment.inline used at the same time

### ISSUE THREAD

**Issue by benzhangyuan** [randyzwitch/RSiteCatalyst#176]
Hi Randy,

I use this package a lot. Thanks for creating it. I ran into this problem recently. I have an existing segment in SiteCatalyst and now I want to run a report with that segment as well as adding an additional inline segment. So I specified both segment.id and segment.inline in a queue function. However, I noticed that the inline segment was not used in filtering data. Does segment.id override segment.inline? Is there a workaround? Thank you.

**Comment by randyzwitch** [comment]
Hey @benzhangyuan, glad you are getting value from the package.

Unfortunately, the more complex the request, the harder it is for me to debug/develop for. Nothing stands out in the RSiteCatalyst code that would make it not possible, but if you're not seeing the desired result, then the implementation must be off.

That said, I don't use the package enough (really, at all) to dig into something this specific. But like #172, #162, #159, if someone were to figure this out, I'd happily merge the code into the package and put out a new release.

**Comment by WillemPaling** [comment]
@benzhangyuan – is this something that you're definitely able to do using the API directly?
Can you try build the request manually using the API explorer?
https://marketing.adobe.com/developer/api-explorer

The doco isn't explicit, but seems to indicate it will take one or more segment IDs, OR and inline segment: https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/r-reportdescription-1

**Comment by benzhangyuan** [comment]
@randyzwitch @WillemPaling Thank you both for the answers. I managed to find a way to get the desired result. Instead of segmenting everything through the queue functions, I first used the segement.id to filter the data and then used R's built-in lookup function grepl() to further filter to get the rows I need. Anyway, thank you!

**Comment by bdhood16** [comment]
@benzhangyuan Would you be willing to elaborate more on the solution you came up with? I'm still trying to work out how to handle using both a segment.id that exists already in my Adobe, as well as an inline. 

Currently I'm getting an error trying to do both an id and an inline at once.

**Comment by walshj** [comment]
Really clunky code here I know... But does this solve the issue (at least in QueueRanked.R)
it allows multiple segments and the addition of inline segment (haven't tested it with multiple inline segments...but don't see why it wouldn't work)
I'm sure someone can better vectorize it but jsonlite kept messing with my specifics
  ```
        seglist <- list()
        for(seg in segment.id){
            tmp.seg<- list(list(id=unbox(seg)))
            seglist <- c(seglist,tmp.seg)
        }
        if(segment.inline != ""){
            seglist <- c(seglist,list(segment.inline))
        }
        report.description$reportDescription$segments <- seglist
```
