### ISSUE TITLE
Mismatch between numbers from QueueSummary and QueueOvertime

### ISSUE THREAD

**Issue by rsudarshan93** [randyzwitch/RSiteCatalyst#178]
I'm facing an issue where a metric is different in a QueueSummary Report and in a QueueOvertime Report. I'm pulling the metric for the same time period and for the same suite.

Further, I checked the numbers against the online platform and found the QueueSummary numbers to be matching with the online platform.

Am I missing out on something here?

Let me know if you need any more info.

Thanks! :)

**Comment by engti** [comment]
What kind of metrics? Some are time bound and as such would throw different values if you tried adding them in from another granularity.

**Comment by rsudarshan93** [comment]
Hey engti! Thanks for the reply.

I'm pulling totalVisits, uniqueVisitors and pageViews.

I pulled one report using QueueSummary with date range as Jan 1, 2015 to Dec 31, 2015 and another report using QueueOvertime for the same range with date.granulrity = "year".

For some suites these values match (for most suites, actually). For some suites there seems to be a difference of 5-10 visits/visitors/pageviews.

It's not an alarming difference. Was just curious what could be wrong.

**Comment by randyzwitch** [comment]
One other general thing to keep in mind. RSiteCatalyst itself does no arithmetic...you can think of the package as being a glorified JSON reader/writer. So if there are cases like this where there are inconsistencies, then this should be what you see in the Adobe Analytics interface as well.

**Comment by rsudarshan93** [comment]
Hey Randy! I get what you mean. The thing is the interface agrees with the QueueSummary report and not with the QueueOvertime report.

I'll look into the granularity part that engti mentioned once again. Just to be sure I'm not missing out on anything.

Thanks! :)
