### ISSUE TITLE
Evaluate merging GetReport and GetReportByIds together into single function

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#182]
@shashispace - 

In looking at the code prior to releasing a new CRAN version, it seems to me that these functions are essentially the same, one taking a single id and one taking multiple ids. Is this true, or is there something else I'm missing?

If they are basically the same function, we should deprecate one of them so that there is only one way to do things.

**Comment by shashispace** [comment]
@mrshashi 

(I'm about to lose @shashispace account)

**Comment by mrshashi** [comment]
@randyzwitch 

GetReport was factored out of SubmitJsonQueueReport, to make it async.

GetReportsByIds does not repeat the logic in GetReport to fetch the reports, it's just a utility function to get a bunch of reports simultaneously. It calls GetReport for individual report when report is ready. It was useful for our project, and I thought it might be useful for others as well.

Thoughts?

**Comment by randyzwitch** [comment]
That makes sense; the most important thing is that it is proven useful. Does `GetReportByIds` work with a single report id? If so, maybe we can just make `GetReport` an internal function, which would remove any confusion.

**Comment by mrshashi** [comment]
Yes, it works with single report id, but it returns a list of lists, where inner list looks like this: `list('report.id'=report.id,'data.frame'=report)`. So one has to extract the report from it.
We could remove `GetReport` from public functions.

**Comment by mrshashi** [comment]
Though my recommendation would be to leave both functions in there - it's not breaking DRY principal, and both have a slightly different use case and signatures and return values. It would be annoying for folks to try to extract report from list of lists, when all they want is a single report. (Having said that, single report could just be fetched from Queue* functions, without using the async feature.)

**Comment by randyzwitch** [comment]
Thanks for the walkthrough @mrshashi, now that I understand the subtleties, I agree that both are doing different things. I'll update the documentation to make the difference more clear for others.

Thanks again for the contribution!
