### ISSUE TITLE
Does QueueFallout work?

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#183]
Not sure if this is a small data issue with my site or fallout not working correctly. Evaluate on large site.

**Comment by dieguico** [comment]
I'll check it tomorrow at work (~1M vistits/month).

**Comment by dieguico** [comment]
As far as I can see it is working correctly.

**Comment by randyzwitch** [comment]
Thanks for validating! I'm building new documentation at http://randyzwitch.com/rsitecatalyst using RMarkdown, maybe I just didn't use a long enough time period.
