### ISSUE TITLE
GetProps() returning only enabled props

### ISSUE THREAD

**Issue by wmcraver** [randyzwitch/RSiteCatalyst#184]
When I run GetProps() on my report suite, it appears to be only returning those that have an enabled value of 'TRUE'.  GetEvars() appears to be returning all eVars regardless of their enabled value.

**Comment by randyzwitch** [comment]
Is this a different behavior than the API Explorer returns? 

At its most reductionist, RSiteCatalyst is only a JSON parser/writer, so if the API only sends enabled props, that's what it returns. If the API Explorer returns all props, then this would be a bug

**Comment by wmcraver** [comment]
Definitely not a bug.  I just tested with the API Explorer and it only returns the enabled props.

**Comment by randyzwitch** [comment]
Great, thanks for confirming!
