### ISSUE TITLE
Include ReportSuite.ViewProcessingRules

### ISSUE THREAD

**Issue by jillsmathew** [randyzwitch/RSiteCatalyst#188]
Adobe API now supports viewing of processing rules using the method ReportSuite.ViewProcessingRules. 
The method accepts "rsid_list" like most ReportSuite API methods and returns the rules with title and description. 
Can you please include this method into the package?

Ref: https://marketing.adobe.com/developer/forum/administration/processing-rules-api

Thanks

**Comment by randyzwitch** [comment]
Merged with #179
