### ISSUE TITLE
QueueSummary function - specifying a custom date range

### ISSUE THREAD

**Issue by jdeboer** [randyzwitch/RSiteCatalyst#191]
The help documentation for the `QueueSummary` function says _"Time period in the date parameter can be specified as year only ("2015"), year-month ("2015-04") or year-month-day ("2015-04-20"); **alternatively, date.to and date.from are available for custom date ranges.**"_. However, `date` is implemented as a required argument resulting in an error when attempting to specify a custom date range as follows:

```{r}
QueueSummary(
  reportsuite.id = staging_RSID,
  date.from = "2016-11-06",
  date.to = "2016-12-03",
  metrics = "visits"
)
```

```
Error in QueueSummary(reportsuite.id = staging_RSID, date.from = "2016-11-06",  : 
  argument "date" is missing, with no default
```

I am new to using this package, so still learning. Please let me know if there is something I can or should be doing to resolve this error.

Thanks.

Johann.

**Comment by WillemPaling** [comment]
Hi Johann,

Is this the RSiteCatalyst doco? Or Adobe doco?

It looks like date is implemented as a required argument, which it shouldn't be:
https://github.com/randyzwitch/RSiteCatalyst/blob/8426c9fe3bf5d417ab46a169b3ba2af0880ee718/R/QueueSummary.R

You might be able to work around it by including date="", even though that should not be necessary.
It should be pretty easy to make the change there and submit a PR if you're happy to do that.

Willem

**Comment by jdeboer** [comment]
Hi Willem! :)

This was in the RSiteCatalyst documentation.

Thanks for suggesting `date = ""`. This seems to be working for me.

Regards,

Johann.

**Comment by WillemPaling** [comment]
If that has got it working, the resolution should be as simple as updating this line.

QueueSummary <- function(reportsuite.ids, metrics, interval.seconds=5, max.attempts=120,validate=TRUE, date="", date.from = "", date.to = "",enqueueOnly=FALSE) {

**Comment by jdeboer** [comment]
Done. Not sure why the continuous integration tests are failing though - seems to be something to do with support for legacy credentials.

**Comment by WillemPaling** [comment]
I suspect the tests fail because they are using some old version of @randyzwitch 's credentials:
https://github.com/randyzwitch/RSiteCatalyst/blob/master/tests/testthat/test-scauth.R

**Comment by randyzwitch** [comment]
The tests fail because TravisCI only puts secure credentials into the repo owners test runs to avoid information leakage. When I merge in the PR, the test suite will run in a fully authenticated manner
