### ISSUE TITLE
Reports not working properly?

### ISSUE THREAD

**Issue by maloneypatr** [randyzwitch/RSiteCatalyst#195]
In general, whenever I try using any function that pulls a report (e.g. QueueRanked, QueueTrended, etc.) or grabs anything report related (e.g. GetQueue) - I'll receive this error:
"ERROR: Bad Request  -  You do not have privileges to perform this operation."

I've been using these functions in an automated weekly script that has been running error-free up until the middle of last week. Not 100% sure if this is due to a change on Adobe's side, or if it's maybe a bug in Report.Validate in this code (and also Report.GetQueue) - basically anything that checks against report privileges?

**Comment by randyzwitch** [comment]
This seems like an account-related issue. I just ran the test suite for this package and got 100+ successful function calls.

**Comment by maloneypatr** [comment]
OK, cool.  Thank you for following up!  I'll let you know if there are any new developments on my end.  Thank again!
