### ISSUE TITLE
QueueDataWarehouse() - length(rows) == 1 is not TRUE

### ISSUE THREAD

**Issue by wmcraver** [randyzwitch/RSiteCatalyst#196]
I'm trying to pull data using the QueueDataWarehouse function.  When the report is received, I receive an error message: `Error: length(rows) == 1 is not TRUE`.  Below is the code chunk that I'm using.  eVar127 is a confirmation number.  I was using this as a test before I throw on all of the other eVars for the pull.

`newX = QueueDataWarehouse(rs, 
                       today()-1,
                       today()-1,
                       metrics = "orders",
                       element = c("evar23"),
                       enqueueOnly = F)`

![rsitecatalyst-qdw-error](https://cloud.githubusercontent.com/assets/622307/21323115/528e8c92-c5d9-11e6-81d7-1281a337fadc.PNG)

**Comment by randyzwitch** [comment]
Thanks for reporting. Are you hoping to be able to use this functionality regularly, meaning, instead of sending to FTP you actually want to return to the console?

I've been thinking about deprecating the ability to return to the console, because I'm not sure I can write a generic enough parser. Right now, there is a test that works against my account, but perhaps it's not sufficiently generic enough: 

```R
  qdw <- QueueDataWarehouse("zwitchdev",
                                    "2016-11-01",
                                    "2016-11-07",
                                    c("visits", "pageviews"),
                                    c("page"),
                                    enqueueOnly=FALSE
  )
```

**Comment by damienCAFR** [comment]
I confirm when you use a FTP, it works. If I send the data directly to the console, I've got the same error message.

And, apparently, Adobe Analytics does not handle an external SFTP server (only a regular external FTP server).

**Comment by randyzwitch** [comment]
Thanks for confirming @damienCAFR. As I posited to @wmcraver, is waiting for a long time and returning to the console actually something you anticipate doing? I didn't develop this method, so I'm not sure how prevalent someone would want to return to the console vs sending to FTP. My gut feeling is to deprecate the ability to return to the console, but didn't want to do so before checking with people.

**Comment by wmcraver** [comment]
Hi Randy,  Sorry for the delay.  I was hoping to wrap the returned results from the data warehouse into another script that I have to process on a daily basis.  We currently don't have an FTP server to store the extracts, so my daily process is to open an email, copy the CSV to a directory, and then fire another script to clean the extract.  It's not a huge deal if it doesn't make the cut, I'm looking to automate as much as I can.

**Comment by randyzwitch** [comment]
No problem Mitch, I was able to avoid using a computer for the last 3 weeks, so I wouldn't have done anything with your response anyway!

Thanks for the use case, I see why that would be useful. I'll have to write some more complicated examples to see how to write a parser that works for many levels of elements.

**Comment by randyzwitch** [comment]
Since this is in-progress with #200, I'm going to close this issue for brevity. Let's all comment on #198 to test the PR from @jdeboer
