### ISSUE TITLE
curl_fetch_memory error

### ISSUE THREAD

**Issue by michaelstenborg** [randyzwitch/RSiteCatalyst#197]
Hi Randy,

Big fan of the package, use it daily at my job.  I have run into this error in SCAuth after upgrading R (3.3.2) and RSiteCatalyst (1.4.10) (and all other dependencies) on our server and was wondering if you have any insight.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

We are using legacy authentication: SCAuth("user:company", "key").

I do not encounter this error on my desktop (which is up to date for R and packages), nor did we have this error before I upgraded R and the package (previous versions - 3.2.2 and 1.4.8).

Edit: I just ran a test calling the exact same code and path of packages - 3.3.2 returns the curl error from SCAuth, 3.2.2 does not.

**Comment by randyzwitch** [comment]
It appears that this might be the same as #194, which unfortunately I have no insight into solving. curl is magic as far as I'm concerned.

**Comment by lorenzobonomi** [comment]
Hello. Could this issue be related to firewall rules? I had the same error when trying to authenticate with RSiteCatalysti in SQL server 2016. I had to change the outbound rules and allo the R local users accounts in Windows Firewall with Advanced Security.

Hope this helps.

**Comment by randyzwitch** [comment]
Thanks @lorenzobonomi.

Unfortunately, I'm not sure there's anything I can do here to help. Good luck, if you find the answer I'd love to know what solved your specific issue.
