### ISSUE TITLE
QueueRanked Error missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by simonbalder** [randyzwitch/RSiteCatalyst#201]
Related to https://github.com/randyzwitch/RSiteCatalyst/issues/122

I have an issue with the latest version. Also, I have two different machines running the same query. One of them is giving the error, the other one is not.

The command 

library(devtools)
install_github("randyzwitch/RSiteCatalyst", ref="version_1_4_1")

Also resulted in a 404 error.

query:

data <- QueueTrended("reportsuite",
startdate,
enddate,
c("visits","pageviews"),
elements = c("product","device"),
classification = "productcategory",
segment.id = "segment",
date.granularity = "day",
top = c("100","100"))
[1] "Requesting URL attempt #1"
[1] "Requesting URL attempt #2"
[1] "Requesting URL attempt #3"
[1] "Requesting URL attempt #4"
[1] "Requesting URL attempt #5"
[1] "Requesting URL attempt #6"
[1] "Requesting URL attempt #7"
[1] "Requesting URL attempt #8"
[1] "Requesting URL attempt #9"
[1] "Requesting URL attempt #10"
[1] "Requesting URL attempt #11"
[1] "Requesting URL attempt #12"
[1] "Requesting URL attempt #13"
[1] "Received trended report."
Error in if (!is.null(elements[i, ]$classification) && nchar(elements[i, :
missing value where TRUE/FALSE needed

**Comment by randyzwitch** [comment]
Thanks for starting a new issue.

First, you definitely don't want to go back to a previous version of RSiteCatalyst, and certainly not 9 releases ago! :)

So the exact same code works differently on two different machines? How do the two machines differ?

**Comment by simonbalder** [comment]
This issue can be closed. I think it had something to do with the R version installed. Both machines are an Azure Virtual Machine. I think one machine did not have the proper R-Server installed. I installed R x64 3.3.1 and miraculously the script worked again.

**Comment by randyzwitch** [comment]
Glad you figured it out, and thanks for letting me know the solution. While I've aimed to not have any platform-specific code in this package, it looks like there might be an unintentional 64-bit dependency somewhere (possibly in one of the imported packages)
