### ISSUE TITLE
Function to FTP download and read Data Warehouse extracts

### ISSUE THREAD

**Issue by jdeboer** [randyzwitch/RSiteCatalyst#202]
For anyone who want to use the `QueueDataWarehouse` function with `enqueueOnly = TRUE`, where one provides details to have the report saved to an FTP server, I thought to share the following as it might be useful to you or to include as part of the `RSiteCatalyst` package.

I've written the following function to download and then parse CSV reports using the `readr` package. The benefit of `readr` is that it automatically handles compressed files and detects the data types of each field.

The following function checks whether the file can be downloaded from the server and will keep trying until `time_out_seconds` has passed, which by default is set indefinitely. An exponential backoff algorithm is applied, in which the time between each retry is doubled on each attempt. Once the file is downloaded, it is then read and parsed by `readr`, and then returned as a `tibble` data frame.

```r
get_csv_report <- function(url, dest_file, overwrite = FALSE, time_out_seconds = Inf) {
  stopifnot(overwrite | !file.exists(dest_file))
  retry <- TRUE
  wait_time <- 1
  start_time <- Sys.time()
  while (retry) {
    tryCatch({
        download.file(url = url, destfile = dest_file)
        retry <- FALSE
      },
      error = function(e) {
        message(e)
        # This would be a good place to add conditional logic
        # statements to check what type of error occurred.
        stopifnot(
          difftime(Sys.time(), start_time, units = "secs") < time_out_seconds - wait_time
        )
        message(paste(". Retrying in", wait_time, "seconds... "))
        Sys.sleep(wait_time)
        wait_time <<- wait_time * 2
      }
    )
  }
  stopifnot(file.exists(dest_file))
  message(paste("Reading:", dest_file))
  readr::read_csv(dest_file)
}
```

The `url` argument is required and should be set to the full URL of where to download the file from, including any username and password information, e.g. `ftp://username:password@hostname.com/csv_report.zip`. Note: the username and password should be URL encoded, e.g.:
```r
paste(
  lapply(c(
      username = "joeblogs",
      password = "p@ssword!"
    ), URLencode, reserved = TRUE
  ),
  collapse = ":"
)
```

The `dest_file` argument is also required and should be set to the path of the destination file to be written to the local file system.

The optional `overwrite` argument is, by default, set to `FALSE` to prevent any existing `dest_file` from being overwritten. Alternatively, set this argument to `TRUE` if you wish to force overwrite in such a case.

**Note:** It is assumed that a server file download error is because the file does not yet exist on the server. I have not designed the function to distinguish this from any other types of download errors, such as access denial, an incorrect URL, a file system error, etc. I'm also unsure at this stage as to what happens if the file is still being written to the server at the time the download is requested. Would this generate an FTP `550` error?

Any feedback or suggestions for improvement are welcomed.

**Comment by randyzwitch** [comment]
You'll probably get a better response to this as a blog post, as the traffic here is quite limited. 

As far as adding something like this to RSiteCatalyst, my overall philosophy has been to not add any functionality that's not specifically part of the API, as I don't want to maintain a larger scope/codebase.

**Comment by jdeboer** [comment]
OK. I don't have a blog site, so happy for you to publish this on yours if you choose. I've found this function useful for obtaining the Data Warehouse extracts and I hope that others do as well.

**Comment by randyzwitch** [comment]
I'm going to close this, if only because it's not really a library issue. If you still wanted to blog about this function, you could do it at Analytics Playbook (another site I set up):

https://github.com/analyticsplaybook/analyticsplaybook.github.io

You can just look at another article as an example; it uses GitHub markdown syntax, I think it's fairly easy to figure out. Once you're done writing, it gets submitted as a pull request, then I'll merge it in and it will be published!

**Comment by randyzwitch** [comment]
@jdeboer This came up in my Adobe Summit talk, so I will probably write this up in a blog post (with attribution of course). It turns out, lots of people are surprised that R can be used for general programming tasks, not just statistics.
