### ISSUE TITLE
Limiting no. of rows in breakdown of a QueueRanked report

### ISSUE THREAD

**Issue by sudhakar0024** [randyzwitch/RSiteCatalyst#203]
I'm relatively new to RSitecatalyst. Is there a way I could limit the number of rows for element 2,3... in the breakdown of QueueRanked output instead of running to 50,000 row limit?
For example, On a page report (being element 1) I want to choose top 10 results with a Device breakdown (element 2- here I need only top 5 rows for each Page) and Browser breakdown (element 3- here I need only top 2 rows for each Device).

Thanks!

**Comment by randyzwitch** [comment]
Use the `top` parameter.
