### ISSUE TITLE
Implement Segments API

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#204]
Continued from #179 with @slin30

**Comment by slin30** [comment]
Been testing some different access account access permissions for another project at work and discovered that the `Segments.*` methods seem to require more than whatever set of privileges "standard" users have; the standard user permissions work with all the functions within RSiteCatalyst I've tested to date (most of them, aside from DW and `SaveRealTimeSettings`). 

The bottom line is that the `Segments.*` functions, including `Segments.Get`, may not be accessible by non-admins, or at the very least, may require an admin to adjust permissions (which is probably just as good as being non-accessible). Also not sure what Adobe's definition of *deprecation* is WRT time frame. 

Just wanted to bring this to your attention.; this by no means affects my decision to contribute (am writing unit tests ahead of getting ready to submit a PR). 

When I authenticate with a non-admin account, here is what I get for the most basic call to `Segments.Get`:

```r
my_all_segs <- call.Get_Segments(accessLevel = "all")
# Error in ApiRequest(body = query, func.name = fun, ...) : 
#   ERROR: Bad Request  -  You do not have privileges to perform this operation.
my_own_segs <- call.Get_Segments(accessLevel = "owned")
# Error in ApiRequest(body = query, func.name = fun, ...) : 
#   ERROR: Bad Request  -  You do not have privileges to perform this operation.
my_shared_segs <- call.Get_Segments(accessLevel = "shared")
# Error in ApiRequest(body = query, func.name = fun, ...) : 
#   ERROR: Bad Request  -  You do not have privileges to perform this operation.
```

**Comment by randyzwitch** [comment]
Nice find, it will definitely be good to highlight that in the RSiteCatalyst documentation.

**Comment by slin30** [comment]
@randyzwitch, I propose we hold off on deprecating `Segments.Get` until I/we can get some clarity from Adobe re:

1. What does *deprecate* mean?
    * And in what time frame? 
1. Will calls to `Segments.Get` always require admin privileges?

Most users are unlikely to have admin rights, so if we do a swap on the underlying method that is called, users might be displeased, to say the least. 

Furthermore, the previous vs. new method are structurally different, i.e. they return different things, and this can be partially, but not completely explained based on account privileges. I haven't had time to investigate further; only realized this yesterday.

All this of course also applies to #205. 

On a related note, I did a bit of refactoring, and now have (and can submit) usable functions for both `Segments.Get` and `CalculatedMetrics.Get`. Both inherit the majority of a base function's params and documentation. Can see via 5b45c131c99644d6bc8c0ad1c6557ed8eeebd2f1 in the private gitlab mirror.

The two exported functions differ only by the `func.name` passed to `ApiRequest`. Looks like we really should get a two-for-one deal, although neither function has complete, ready-to-export parsing in place for calls that request the field  `definition` (yet).

**Comment by randyzwitch** [comment]
That makes perfect sense to keep `GetSegments` and `GetCalculatedMetrics` until they no longer return an answer. If I get the chance while at Summit, I'll get clarification

**Comment by slin30** [comment]
Sounds good. I've also created a [thread in the support forum](https://marketing.adobe.com/developer/forum/administration/reportsuite-getsegments-vs-segments-get), so we'll get to the bottom of this one way or another.

**Comment by slin30** [comment]
We have a resolution, I think. For whatever reason, the following group permission within *Analytics Tools* must be ticked (boxed in red in screenshot below):

![webservices](https://cloud.githubusercontent.com/assets/13291275/24262212/cde3bbc0-0fcf-11e7-99dd-ba788299a24d.png)

I can access all the other read methods with a non-admin account as long as *Web Services* is checked , but `Segments.Get` and `CalculatedMetrics.Get` both require that *Web Services Access* also be checked. 

As for `ReportSuite.GetSegments` versus `Segments.Get`, here is what Hyrum Tanner of Adobe had to say, in the aforementioned thread in the Adobe dev forum:

> ReportSuite.GetSegments has been deprecated since the release of the Segments API module. It will continue to work until the EOL for the API 1.4 which is years away. The main reason to not use it any more is that the information it returns is incomplete.

I assume the same would apply to the deprecated version for calc metrics.

**Comment by randyzwitch** [comment]
Pretty sure that Web Services Access has always been required, no? Isn't that what assigns an API key to a user?

That's good you got some clarification about GetSegments and GetCalculatedMetrics. Sounds like it's not much of an issue to worry about, and we can slowly phase it out of RSiteCatalyst.

**Comment by slin30** [comment]
That would make sense; it's weird that our non-admins were (are) able to access Web Services, period, without having ticked the *Web Services Access* option. I also assume that we are not that special in terms of our configuration, i.e. if we have it set up this way, surely so do others, so it might be worth noting somewhere when I finally get around to finishing these two sets of functions. 

Have been swamped with work, but getting there. Writing more tests, documentation, and error handling. Core functionality is in place.

**Comment by revolutionbruin** [comment]
I am an admin user my instance of Adobe and tried swapping out the func.name to Segments.Get with an appropriate JSON request. But seem to be getting back a response that looks like a ReportSuite.GetSegments request. (ID and Names vs specific JSON definitions of the segment)

Not sure if I somehow cached a response while testing the GetSegments function you built previously and R is making the same request vs sending the new Segments.Get request.

Do you have any thoughts on how I can debug?

I'd love to help this project along in anyway i can.

**Comment by revolutionbruin** [comment]
I actually fixed my issue by building my JSON request using JSON lite vs a character string.

But, I am still interested in helping anyway I can.

**Comment by randyzwitch** [comment]
Thanks for your offer to help @revolutionbruin. There's an open pull request for this functionality https://github.com/randyzwitch/RSiteCatalyst/pull/220, I just need to find time to review it. My hope is to do that soon.
