### ISSUE TITLE
QueueDataWarehouse doesnt seem to work when elements has multiple classifications

### ISSUE THREAD

**Issue by ratraspringboard** [randyzwitch/RSiteCatalyst#210]
Hi Randy,

I am working on a project to extract bulk data from Adobe using RSiteCatalyst. 

My code is as below :
data <-QueueDataWarehouse(my.rsid, start.date, end.date,
                          metrics, elements,
                    enqueueOnly = FALSE)

My problem is that "elements", have multiple[read 14] "classifications". However, the output is returning only the "first" classification.Somehow the nesting/recursion doesn't seem to work.

Please help on this.

B/R
Vishal

**Comment by randyzwitch** [comment]
Are you able to do the report you want from the Data Warehouse interface in Adobe Analytics?

Also, what is the actual code that you tried to submit? The snippet you provided is no more than the function stub itself, so it doesn't help determine if this is an RSiteCatalyst issue or a user syntax issue.

**Comment by ratraspringboard** [comment]
Hi,

Yes, i am able to pull out the report from Adobe Analytics giving the same parameters

The actual code is:

====
suites <- GetReportSuites()
my.rsid <- suites[suites$site_title=="myreport_suite",1]
data <-QueueDataWarehouse(my.rsid, "2016-01-01", "2016-01-02",
                          "visits", "prop14",
                    enqueueOnly = FALSE)

=====
Doesn't seem to have a problem with code as it gets information, but only extract the first "classification
variable" is extracted 

![image](https://cloud.githubusercontent.com/assets/21958215/23308352/f6fc03fa-fad0-11e6-9b0e-4cb0d8cd9eda.png)

As you can see that the "prop14" element is internally having other classification variables and the code seems to pick up only the first one which is User email address.

Also,Is there a way to directly feed in "classification" variable in the elements parameter in QueueDatawarehouse function, I tried multiple combinations like prop14.Country, prop14:Country all seem to be in vain

**Comment by EmilBrink** [comment]
Hi Randy, hi Vishal,

is there any updates for this issue? @ratraspringboard I would like to know if you have found a way to solve you issue, because I also have a familiar one.

B/R Emil

**Comment by ratraspringboard** [comment]
Nothing that i know of.

Thanks,
Vish

**Comment by drose76** [comment]
Was ever solved by anyone?

**Comment by slin30** [comment]
I believe `QueueDataWarehouse()` can accept a `classification` arg. Needed to do this today and tested an ugly ad-hoc hack, and got results-- need to test and validate, but seems promising.

@randyzwitch : this is probably quite easy for you to implement, but I know you don't really do much with Adobe Analytics these days, so happy to take this on a submit a PR when I've properly tested (would expect a couple weeks). Thoughts?

**Comment by randyzwitch** [comment]
@slin30 No, this isn't something I'm going to work on, but I'm happy to review a PR if you submit it

**Comment by slin30** [comment]
Noted. Will start working on this.
