### ISSUE TITLE
Rsitecatalyst + sankey charts

### ISSUE THREAD

**Issue by XoliloX** [randyzwitch/RSiteCatalyst#213]
Hi All,

I recently tried to do sankey charts with this code (http://randyzwitch.com/rsitecatalyst-website-pathing-sankey-charts/) but the html output is blank. Then, I noticed that the package d3Network was not updated anymore and replaced by networkD3 (https://christophergandrud.github.io/networkD3/) but then, since I'm new to R, I could not get it working either. Would anyone know how to easily link an excel file (from Adobe) to a code generating a sankey chart ? 

In advance, thanks a lot for your help !!!

Regards,
D.

**Comment by randyzwitch** [comment]
Thanks for letting me know that the example doesn't work any more, I'll try and fix that.

How does the Excel file you are talking about fit in here? Is it something you can share?

**Comment by XoliloX** [comment]
Hi Randy,

Thanks for your answer. Here attached is a file compiled thanks to your Rsitecatalyst script :

![image](https://cloud.githubusercontent.com/assets/1244126/24258607/984ef3fc-0fee-11e7-9864-927fb90a3c3c.png)

The idea would be to have such file visualized with a sankey chart.

Thanks a lot in advance for your answer !

D.

**Comment by randyzwitch** [comment]
Thanks for clarifying @XoliloX. It's not clear from your example that this data is in the proper format for a Sankey diagram. Your file should be something like the following, where there is a start and end to the path:

<img width="870" alt="screen shot 2017-03-26 at 3 36 02 pm" src="https://cloud.githubusercontent.com/assets/2762787/24334546/05d8dc2e-123a-11e7-9933-222d71e33288.png">

**Comment by randyzwitch** [comment]
FWIW, the code example on this page does work from beginning to end (for my credentials):

http://randyzwitch.com/rsitecatalyst-website-pathing-sankey-charts/

So I'm going to close this issue as its not a package error per se, but I'll keep in mind to use the networkd3 package in the future if I do any more examples like this.

**Comment by XoliloX** [comment]
Hi Randy,

Thanks for the clarification. Still, when I copy the script and adapt with my credential, the output is empty ; how would you solve this issue ? In addition, let's say that I'll use an excel file formatted as the one you shared, how would you enable your script to take the data from it ?

Thanks a lot in advance for your answer !

D.

**Comment by randyzwitch** [comment]
Unfortunately, there isn't a good way for me to debug what the issue might be. It works for me still using OSX and Chrome; maybe use the Javascript console in whatever browser you are using to see if there is an error?

For Excel files, you can read them in using the `readxl` package.

https://github.com/tidyverse/readxl

**Comment by XoliloX** [comment]
Ok, thanks a lot !
