### ISSUE TITLE
ViewProcessingRules: Differing Number of Rows Error 

### ISSUE THREAD

**Issue by riastrad** [randyzwitch/RSiteCatalyst#214]
When calling the new ViewProcessingRules function on a report suite that has multiple processing rules with varying logic, I am seeing the following error:

```
> pr <- ViewProcessingRules("my-report-suite-id")

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 20, 80, 1, 2, 3, 14, 4, 26
```

**Comment by randyzwitch** [comment]
Thanks for reporting. Would you be willing to email me the JSON string that's returned if you set `debug.mode=TRUE` in `SCAuth()`. My email is in the RSiteCatalyst DESCRIPTION file.

If you can, that would help me out greatly. If you can't, it might take me a bit to fix this, as I don't have an in-depth processing rules example to test against.

**Comment by riastrad** [comment]
Since it's a client's implementation, I'll have to get prior approval and will likely have to scrub some of the information regarding variable names. Would this still be helpful for your purposes?

**Comment by randyzwitch** [comment]
If you can, great, if not, no big deal. I don’t really care what data is in the file, I just need to see what the returned JSON structure is and how it differs from what I saw to do my implementation originally.

**Comment by riastrad** [comment]
Just received approval from the powers that be. I've sent the file to the e-mail listed in the DESCRIPTION file. Please let me know if you need anything more to troubleshoot effectively.

**Comment by randyzwitch** [comment]
This helped immensely, now I see why my original parsing logic is incorrect. Hopefully I'll be able to get a fix out by the end of the week that you can test.

**Comment by randyzwitch** [comment]
If you're a devtools user, I pushed what I think is the fix for this to master.

```R
library(devtools)
install_github("randyzwitch/RSiteCatalyst")
```

**Comment by riastrad** [comment]
I wasn't familiar with devtools before, but it wasn't hard to pick up for this task.

The fix that you pushed to master works exactly as expected. I tested it on a half dozen data suites and all of them returned a valid response.

**Comment by randyzwitch** [comment]
Great, thanks for testing! I’m going to close this issue, and the fix will be pushed out to everyone with the next RSiteCatalyst release.
