### ISSUE TITLE
QueueDataWarehouse segments not working

### ISSUE THREAD

**Issue by erollinsTLU** [randyzwitch/RSiteCatalyst#216]
I'm using the QueueDataWarehouse function and it's working fine, except that the data is not being filtered by segment. A code snippet demonstrating this is as below:

`data <- QueueDataWarehouse(reportsuite.id = "[reportsuiteID]",
                                      date.from = "2017-01-01",
                                      date.to = "2017-03-31",
                                      metrics = c("visits", "pageviews", "uniquevisitors"),
                                      elements = c("page", "evar16", "geoCountry", "geoRegion", "firsttouchchannel", "mobiledevicetype"),
                                      date.granularity = NULL,
                                      segment.id = c("[segmentID]"),
                                      data.current = FALSE,
                                      expedite = FALSE,
                                      interval.seconds = 5,
                                      max.attempts = 100,
                                      validate = FALSE,
                                      enqueueOnly = FALSE)`

Despite trying over a dozen different segments, from more complex to extremely basic (all able to be viewed in Data Warehouse in Analytics), the report being generated is identical to the one generated with no segments selected.

Cheers

**Comment by randyzwitch** [comment]
If you're a devtools user, I pushed what I think is the fix for this to master.

```R
library(devtools)
install_github("randyzwitch/RSiteCatalyst")
```

**Comment by randyzwitch** [comment]
Closing this issue, but if the fix pushed to master doesn't work for you, let me know. I'll be sending this fix to CRAN in the next week or so (along with a handful of others)

**Comment by erollinsTLU** [comment]
Hi Randy,

Thanks for getting to this quickly. Still seeing much of the same issue. While there is at least some correct data feeding through, seeing some ridiculous data come through like the same number of visitors and visits from a very small segment compared with all visitors.

If you'd like any more info let me know.

Evan

**Comment by randyzwitch** [comment]
There's a few issues wrapped up together here. For the most part, RSiteCatalyst just returns what the API returns. Do you get the same answer from the Data Warehouse UI in Adobe Analytics as you get from RSiteCatalyst? If so, that's a success to me. 

If you get a different answer from the Adobe Data Warehouse UI than in RSiteCatalyst, note that for whatever reason the API that RSiteCatalyst calls only allows for one segment, where the Data Warehouse UI allows for multiple segments. So double-check that your RSiteCatalyst statements aren't passing multiple segments; I would've assumed that the API would throw an error if you passed multiple segments.

If you still get different answers for the same segment from the Data Warehouse UI and RSiteCatalyst, I'm not sure what to suggest.
