### ISSUE TITLE
Error enqueueing reports: ERROR: Collections service error: errorId= -

### ISSUE THREAD

**Issue by arfuzzum** [randyzwitch/RSiteCatalyst#217]
We enqueue reports in a for-loop on a set of segment combinations (due to lib limitations on using several elements when first element is a classified element):

`mr.ids <- NULL

for (i in 1:12) {
  
  mr.id <- QueueTrended(
    reportsuite.id = rs,
    date.from = mfd,
    date.to = mtd,
    date.granularity = "month",
    top = 50,
    elements = "prop4",
    classification = "Category (all hits)",
    metrics = sel.m,
    segment.id = c(seglist[i,1],seglist[i,2]),
    enqueueOnly = TRUE
  )
 mr.ids <- c(mr.ids,mr.id)
}
`
seglist contains 12 sets of segment combinations

Occasionally we get the following response/error:
`[1] 500
Error in ApiRequest(body = report.description, func.name = "Report.Validate") : 
  ERROR: Collections service error:  errorId=  -  `

A report config that fails / throws an error might work when rerunning.

**Comment by arfuzzum** [comment]
I could also mention that I am getting other errors as well:
`
503
Error in ApiRequest(body = report.description, func.name = "Report.Queue") : 
  ERROR: calculated_metrics_unavailable  -  Calculated Metrics are currently unavailable
`

I have checked the Adobe API documentation, but cannot find such an error code. Further I have checked with status.adobe.com, and no known issues are published. Also, I have used the Adobe API Explorer to check a similar request using calculated metrics, which worked fine.

I am not sure where this could be pointing. Any information on how RSitecatalyst would handle network instabilities, for example?

**Comment by randyzwitch** [comment]
The 500 error is purely an Adobe error, there's nothing RSiteCatalyst could do (outside of adding an auto-retry, which isn't high on my priority list).

For the 503 error, this link may help: https://marketing.adobe.com/developer/documentation/data-warehouse/r-report-2

Specifically "A single segment is supported. Multiple segments are not supported.

Calculated metrics are not supported and will not return in the call to Report.GetMetrics when "reportType":"warehouse"."
