### ISSUE TITLE
GetLogin now returns (additionally) create_time

### ISSUE THREAD

**Issue by slin30** [randyzwitch/RSiteCatalyst#218]
Hi Randy, 

Am giving you a heads-up since this is probably my doing, re: this thread in the dev admin forum:

https://marketing.adobe.com/developer/forum/administration/get-create-time-and-expires-via-api

Unexpectedly (but happily, since we wanted this field), an internal user mentioned that my custom *Permissions.GetLogin* parsing function was throwing an error, and it turns out that it's due to the new `create_time` field. The list of fields is now:

| idx|field_name              |
|---:|:-----------------------|
|   1|selected_ims_group_list |
|   2|login                   |
|   3|first_name              |
|   4|last_name               |
|   5|title                   |
|   6|email                   |
|   7|create_time             |
|   8|phone_number            |
|   9|is_admin                |
|  10|must_change_password    |
|  11|is_temp                 |
|  12|temp_start_date         |
|  13|temp_end_date           |
|  14|group_names             |

Since there are a total of `14` fields, `GetLogin` will need to be tweaked to extend the column index range.

**Comment by randyzwitch** [comment]
Seriously? I swear I just fixed this method and it worked, now they add another field?

https://github.com/randyzwitch/RSiteCatalyst/commit/5977d083849f3683bb3e2d14e564a1856d3a9d38

**Comment by randyzwitch** [comment]
Closing this...as I went through the test suite, got this message:

```R
 Error in ApiRequest(body = toJSON(request.body), func.name = "Permissions.GetLogin") : 
  ERROR: Bad Request  -  Cannot get login information in Analytics when IMS migration is in progress or complete. Users should be managed via the marketing cloud. 
```

Doesn't appear that this method works any longer, though I won't deprecate it in case anyone else happens to have an environment where it works.
