### ISSUE TITLE
RSiteCalalyst Authentification error on R-3.4.0 

### ISSUE THREAD

**Issue by mohamedndiaye** [randyzwitch/RSiteCatalyst#219]
Hi
I tried RSiteCalalyst on R version 3.4.0  but have an error while authenficating 

> SCAuth('xxxxxxxx:XXX','XXXXXXXXXXXXXXXXXXXXXXXXXXXX')
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

Do you have any ideas ?

**Comment by randyzwitch** [comment]
It's working for me. Generally, curl errors are masking network issues like not having a good Wi-Fi connection

**Comment by mohamedndiaye** [comment]
yes ...I tried with my personnal computer at home. It works 
The previous error must ne relatée to The proxy at work.....i'll look for issues...

**Comment by phillyo** [comment]
@mohamedndiaye how have you resolved this issue? i'm facing the same issue as you have for 3 different wifi networks...

**Comment by mohamedndiaye** [comment]
I am sorry I did not succed
