### ISSUE TITLE
Error: calculated_metrics_unavailable  -  Calculated Metrics are currently unavailable

### ISSUE THREAD

**Issue by j450h1** [randyzwitch/RSiteCatalyst#221]
`Error in ApiRequest(body = toJSON(request.body), func.name = "Report.Get",  : 
  ERROR: calculated_metrics_unavailable  -  Calculated Metrics are currently unavailable
Calls: source ... QueueTrended -> SubmitJsonQueueReport -> GetReport -> ApiRequest
`

Anything that can be done other than retrying at a different time?

**Comment by randyzwitch** [comment]
Can you post the code that generates this error? It's not clear to me what the problem might be

**Comment by j450h1** [comment]
Thanks Randy. As usual, I believe it was just an Adobe server side issue as the pull seems to be working fine now.

**Comment by revolutionbruin** [comment]
Just an FYI... I was running into this issue with a third party tool that autogenerates the API query based on selected metrics. Certain metrics are not allowed to be broken down by other granularities. I believe these settings are available via the ReportSuite.GetMetrics API call. I am actively working with Adobe support to understand this better and will post feedback when i get it.
