### ISSUE TITLE
unable to login with OAUTH2

### ISSUE THREAD

**Issue by leocwlau** [randyzwitch/RSiteCatalyst#223]
it seems Adobe had changed the token returned from oauth2.0_token method. It is now something like:

<oauth_endpoint>
 request:   https://marketing.adobe.com
 authorize: https://marketing.adobe.com/authorize
 access:    https://api.omniture.com/token
<oauth_app> RSiteCatalyst
  key:    xxxxxxxxxxx
  secret: xxxxxxxxx
`<`credentials`>` access_token, expires_in, token_type, scope, success

This breaks the following code as sc.cred$access_token, sc.cred$scope, sc.cred$client_id, and sc.cred$expires are all NULL
      scc <- list(endpoint.url=endpoint.url,
                               auth.method=auth.method,
                               access_token=sc.cred$access_token,
                               scope=sc.cred$scope,
                               client_id=sc.cred$client_id,
                               expires=sc.cred$expires,
                               debug = debug.mode,
                               locale = locale
                               )

I had cloned the RSiteCatalyst source and rebuilt with the following
scc <- list(
  endpoint.url = endpoint.url,
  auth.method = auth.method,
  access_token = sc.cred$credentials$access_token,
  scope = sc.cred$credentials$scope,
  client_id = sc.cred$app$key,
  expires = sc.cred$credentials$expires_in,
  debug = debug.mode,
  locale = locale
)

**Comment by randyzwitch** [comment]
Thanks for reporting this. Is this something you are willing to submit as a pull request?

**Comment by leocwlau** [comment]
will do. moreover, it seems there are still two outstanding issue from the OAUTH:
1. no token refresh after expire
2. access grant error if manually delete .httr-oauth for re-authentication

**Comment by randyzwitch** [comment]
Fixed by #224, merging to master and submitting to CRAN shortly
