### ISSUE TITLE
Accessing integrated variables using RSiteCatalyst

### ISSUE THREAD

**Issue by SiteCatExplorer** [randyzwitch/RSiteCatalyst#225]
Hi, I was trying to make use of RSiteCatalyst package to automate a few regular reports. The variables I use in Sitecatalyst are the ones integrated through Adobe Target in SiteCat. However, on retrieving the elements , props I am not able to view these integrated dimensions in R. Do you think this can be possible?

**Comment by randyzwitch** [comment]
There are two questions here:

1) Does the Adobe API allow for retrieving this data?

Unfortunately, I don't know the answer to this off the top of my head.

2) Can this be implemented? 

Depending on the answer to 1), someone could implement this if the API provides the information. Unfortunately, I don't have access to an account for Target, so I wouldn't be the person who can do this. But I'd accept a patch were someone to submit one.

**Comment by WillemPaling** [comment]
These should be available like normal dimensions to submit in a ranked or trended report. I have done this plenty of times. Try looking for 'experience' in the results of GetElements()

Are you using the A4 integration?

**Comment by SiteCatExplorer** [comment]
@randyzwitch  Yes the API allows for the retrieval of this data

@WillemPaling  I did expect these variables to appear in the results for GetElements. However, in the experience related variables I am unable to find the same dimension (Target Activity which contains the test campaign name). The variables which I am currently able to access are the campaign keys (54481:1:0 in this format) and based on the results I see I don't think it contains all the values. 
Also A4 integration is being used here. Fairly new to this, if you could help me understand in case I'm looking at this incorrectly.

**Comment by randyzwitch** [comment]
Closing this as @WillemPaling confirmed its not a library-related issue. Please feel free to continue commenting here if you'd like, though I will not be able to help
