### ISSUE TITLE
Error: could not resolve host name ( Please help )

### ISSUE THREAD

**Issue by digital212** [randyzwitch/RSiteCatalyst#227]
Hi, 

I have tried to use this package on my own computer and it works fine. 
But when I try to use it within the company network. It give me the error : 
error in curl . Couldn't resolve host name. 

I have asked IT team to looked into this problem. But they can not find what caused the error. 
Can you please answer few questions raised by them ?
1. Is R a proxy aware application ( can we set up proxy)?
2. If it is not using http/https connections to connect adobe analytics , what port does it use?

Many thanks !

**Comment by randyzwitch** [comment]
Unfortunately, this isn't something I can help with, as it's most certainly a problem within your company network. The package calls https://api.omniture.com, but I believe there are up to 6 versions: https://api2.omniture.com, https://api3.omniture.com...https://api5.omniture.com.

I have no idea about the answer to question 1, but if your IT is asking about that, then they must realize the problem is in their network.

**Comment by digital212** [comment]
Hi @randyzwitch ,

I used the code below and fixed the host issue. Now I can use Rsitecatalyst to connect adobe !
Hopefully it can help people who had the same proxy issue. 

#set http proxy due to company's firewall
companyproxy <- curl::ie_proxy_info()$Proxy
Sys.setenv(http_proxy=companyproxy)
Sys.setenv(https_proxy=companyproxy)

#curl https webpage
curl::curl_download("https://httpbin.org", "C:/temp/https.html")
curl::curl_download("https://www.google.com", "C:/temp/https.html")

**Comment by randyzwitch** [comment]
Thanks for the update. Just to be clear, this is all you need right?

```R
library(curl)
companyproxy <- curl::ie_proxy_info()$Proxy
Sys.setenv(http_proxy=companyproxy)
Sys.setenv(https_proxy=companyproxy)
```

If so, I can add this to the RSiteCatalyst documentation, so that others can benefit.

**Comment by digital212** [comment]
Hi @randyzwitch 

I have tried in my colleague's computer. 
And this is the only setup I did before running Rsitecatalyst. 
And it worked for us. 

Regards
