### ISSUE TITLE
Vector Length error - ShinyApp 

### ISSUE THREAD

**Issue by samistat08** [randyzwitch/RSiteCatalyst#228]
Hello, thank you for your useful page. I am running a shinyApp and the app page appears for a sec and then disappears with following error,

```
Warning: Error in <-: 'names' attribute [8] must be the same length as the vector [7]
Stack trace (innermost first):
    41: structure
    40: server [#7]
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>
Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
  'names' attribute [8] must be the same length as the vector [7]

```
I have installed the recent version of RSiteCatalyst, 1.4.13, but the problem stays remained. I would appreciate your tips and help.

**Comment by randyzwitch** [comment]
Without seeing the code that generates this error, it's difficult to me to suggest what the fix might be. What does the Shiny app do, and has this ever worked (i.e. a new problem) or is this something in active development?
