### ISSUE TITLE
Data Warehouse Reports Requesting 120 Times Before Failing

### ISSUE THREAD

**Issue by ericbrownaustin** [randyzwitch/RSiteCatalyst#231]
I am trying to pull Data Warehouse reports, however, my script requests URL 120 times before failing.  Is this a normal issue for the API?

`QueueDataWarehouse(id,
                   date.from = "2016-01-01",
                   date.to = "2017-07-31",
                   metrics = c("visits", "pageviews", "event27"),
                   date.granularity = "day",
                   elements = c("visitnumber","entrypage", "geocountry","mobiledevicetype"),
                   interval.seconds = 5,
                   enqueueOnly = F)`

![image](https://user-images.githubusercontent.com/11723172/31778579-a332ec8e-b4b6-11e7-9c17-89d99aa8eb33.png)

**Comment by randyzwitch** [comment]
Yes, this is somewhat expected. There is no guarantee that the Adobe Data Warehouse API will return a result in a short period of time. By default, RSiteCatalyst checks every 5 seconds, up to 120 times. If you need more time than that, you can either increase `max.attempts`, `interval.seconds` or use `enqueueOnly=TRUE` to write to an FTP when the report is finished.

**Comment by ericbrownaustin** [comment]
Is there a suggested update I should make?  Either changing max attempts, internal seconds or both?
