### ISSUE TITLE
QueueDataWarehouse now supports multiple segments

### ISSUE THREAD

**Issue by slin30** [randyzwitch/RSiteCatalyst#239]
Have tested multiple times now, with up to four simple segments via the `segment.id` arg. I assume this is yet another undocumented change, as the referenced page in the function doc:

https://marketing.adobe.com/developer/documentation/data-warehouse/r-report-2

...no longer exists. 

I assume the limitations here (all) still apply:

https://marketing.adobe.com/resources/help/en_US/analytics/segment/seg_compatibility.html

The tests I performed all use single-container segments with rules all `AND`ed or `OR`d together. 

The generic call structure I've used successfully to date (not to say other variations won't work-- but this is all I've tried thus far):

```{r}
List of 10
 $ date.granularity: chr "year"
 $ date.from       : Date[1:1], format: "2017-04-01"
 $ date.to         : Date[1:1], format: "2018-03-31"
 $ reportsuite.id  : chr "xxxxx"
 $ metrics         : chr [1:2] "uniquevisitors" "visits"
 $ elements        : chr [1:2] "xxxx" "xxxx"
 $ enqueueOnly     : logi TRUE
 $ validate        : logi FALSE
 $ segment.id      : chr [1:4] "segID_01" "segID_02" "segID_03" "segID_04"
 $ ftp             :List of 6
  ..$ host     : chr "ftp.xyz.com"
  ..$ port     : chr "21"
  ..$ username : chr "me"
  ..$ password : chr "mypassword"
  ..$ directory: chr "/mydir/"
  ..$ filename : chr "myfile.csv"
```

**Comment by randyzwitch** [comment]
I believe this is closed by #248, but if not, let me know and I'll re-open
