### ISSUE TITLE
QueueFallout returns error.

### ISSUE THREAD

**Issue by njorgz** [randyzwitch/RSiteCatalyst#241]
Greetings!

Yesterday I used QueueFallout with no disruption. The fallout path was:

```{r}
fallout_path <- c("Page 1", "Page 2")
```

However, today when using the QueueFallout, with yesterday's fallout path or a new, web page specific, fallout path, I receive the error below:

```{r}
fallout_path_1 <- c("Page 1","Page 2")
fallout_path_2 <- c("http://domain.com/category/page-1","http://domain.com/category/page-2")

queue_fallout_pages <- QueueFallout(reportsuite_id,
                                    date.from ="2018-08-01",
                                    date.to ="2018-10-01",
                                    metrics ="pageviews",
                                    element="page", 
                                    checkpoints=fallout_path_1) # Or fallout_path_2
```
I receive the error:

```{r}
Error in ApiRequest(body = toJSON(request.body), func.name = "Report.Get",  : 
  ERROR: response_error  -  Expecting data for checkpoint ""
```

I have been looking around for documentation on the error, but have found nothing. Admittedly, I have been using Omniture and RSiteCatalyst for less than 48 hours, so this is probably operator error.

Any insight on the error? 

Thanks!

**Comment by randyzwitch** [comment]
Closing this issue, as it appears to be on Adobe's side. The code around this method hasn't changed, so if there are intermittent issues, I would contact your Adobe rep and ask them to provide assistance around whatever SLAs your contract may specify.
