### ISSUE TITLE
GetReportSuites returning curl error

### ISSUE THREAD

**Issue by ericbrownaustin** [randyzwitch/RSiteCatalyst#242]
After running SCauth script then running GetReportSuites this error is returned:

`Error in curl::curl_fetch_memory(url, handle = handle) : 
  Port number ended with 'B'`

**Comment by randyzwitch** [comment]
In my experience, errors like these tend to occur from network security settings at a given employer, not RSiteCatalyst itself. Have you successfully used this package before, or is this your first time?

**Comment by ericbrownaustin** [comment]
This was due to a authentication error where I had the incorrect secret and username.  Not sure why the error was passed on an auth error.  I can pass extra detail if you'd like in order to update errors if you'd like.

**Comment by randyzwitch** [comment]
Glad you got it figured out.

I don't use the package much these days, so improving the error message isn't a high priority for me. But if you'd like to submit a PR with a fix, I'd be happy to review it.
