### ISSUE TITLE
Too Many Requesting URL attempts

### ISSUE THREAD

**Issue by arjun0907** [randyzwitch/RSiteCatalyst#245]
Hi, 

I am using the QueueTrended function to pull some data specifically "Microsoft Internet Explorer 11" browser from multiple rsids. It takes around 35-42 attempts to get the report for one rsid. Is there any explanation for this or is there a way where I can reduce the number of attempts to get the reports?

**Comment by randyzwitch** [comment]
There's really two parts to this question: why do requests take so long, and why does RSiteCatalyst ping the API so many times.

The first part is on Adobe; any given request takes as long as it takes, there's nothing I can do about that. The second part is that there's no good answer on how long it will take to return any given answer, so re-checking is necessary. This is configurable using the `interval.seconds` parameter.

By default, `interval.seconds` is set to 5 seconds, which in my experience is pretty reasonable. If your report takes 40 attempts on average to return, then set `interval.seconds=200` and on average, you'll only need one attempt to retrieve the report. That said, if it doesn't return it 200 seconds, you'll need to wait 200 more seconds before RSiteCatalyst tries to retrieve it again.

But regardless of how you set the retry time period, the report takes as long as it takes for the Adobe API to return an answer. In your example, the result will take 200s, regardless of the settings in RSiteCatalyst.
