### ISSUE TITLE
*** caught segfault *** address xxxxx, cause 'memory not mapped'

### ISSUE THREAD

**Issue by Venkat6134** [randyzwitch/RSiteCatalyst#247]
In my R script, we are using RSiteCatalyst package.

library(RSiteCatalyst)
SCAuth("Auth", "Authcode")
When we run it we are getting this below error:

Loading required package: RSiteCatalyst

* caught segfault * address XXXXX, cause 'memory not mapped'

Can you please help?

**Comment by randyzwitch** [comment]
I take it that you've addressed #246.

I don't have a Solaris server to test on, so it's going to be difficult to troubleshoot what this might be. One thing I can say is that it's unlikely to be an RSiteCatalyst problem, as this package is written in pure R. It's dependencies do rely on R packages written in C++, and that's likely where any segfaults or memory management issues are happening

**Comment by Venkat6134** [comment]
We have created a new test script with the below two lines, even though its failing with the same error: library(RSiteCatalyst) SCAuth("Auth", "Authcode")
is there any dependent packages versions issue ?

**Comment by randyzwitch** [comment]
Because I do not have a Solaris server, there is no way for me to validate what the issue might be. I suspect that any problem would be with httr, which uses the curl C library.

**Comment by Venkat6134** [comment]
We have reinstalled the httr, and tested the R script. Still we have the failures with the same error.
At least its not giving any more information regarding the failure like location or path or file.
I think you have to test it for Solaris servers as well.

**Comment by randyzwitch** [comment]
To be clear, I don't _have to do_ anything. RSiteCatalyst is an open-source package, of which no warranties or formal support is implied. I have never been an Adobe employee, haven't done digital analytics for almost 7 years now, and have zero access to a Solaris server. 

In your case, you are both paying Adobe and presumably Oracle, so I suggest you contact one of their professional services arms to help you debug this.
