### ISSUE TITLE
GetUsageLog() not an exported function?

### ISSUE THREAD

**Issue by abidawson** [randyzwitch/RSiteCatalyst#256]
I'd like to use this function to export my AA usage logs but it looks like it's not an exported function from the package. When I try to call the function I get the error below. Is there a reason this isn't an exported function, or can it be updated to be exported? I'm on version 1.4.16 installed from cran.

Thanks so much for this package, it's a game changer for my team!

```Error: 'GetUsageLog' is not an exported object from 'namespace:RSiteCatalyst'```

**Comment by randyzwitch** [comment]
Hi @abidawson, thanks for checking out RSiteCatalyst. Glad you are getting value from it!

I wasn't as disciplined with my pull requests as I could've been all those years ago, but I suspect I made the function internal after it stopped working correctly. It's probably the case that the Adobe API doesn't return the result any more, and then my tests failed, so I disabled the function.

If you're able to take a look at this and submit a PR, if it works I'm happy to re-enable it. I haven't done digital analytics in many years, so I don't plan on working on this codebase in the near future.

Best,
Randy

**Comment by slin30** [comment]
@abidawson : this still technically works, but I am not sure for how much longer. I made a few simple modifications to the (non-exported) version and tested just now. Assuming you have sufficient privileges, you should get a result:

```r
getusagelog_alt <- function(date.from=as.character(Sys.Date()-1)
                            ,date.to=as.character(Sys.Date())
                            ) {
  
  request.body <- c()
  request.body$date_from <- jsonlite::unbox(date.from)
  request.body$date_to <- jsonlite::unbox(date.to)
  
  #Hack in locale, every method calls ApiRequest so this hopefully works
  #Set encoding to utf-8 as well; if someone wanted to do base64 they are out of luck
  request.body$locale <- unbox(RSiteCatalyst:::AdobeAnalytics$SC.Credentials$locale)
  request.body$elementDataEncoding <- unbox("utf8")
  
  usagelog <- ApiRequest(body=jsonlite::toJSON(request.body),func.name="Logs.GetUsageLog")
  
}
```
The version in the package was working for a while as-is, but then Adobe made some changes to the return structure, so a few minor modifications were needed. In any event, I keep expecting this to fail in some new, unexpected way, or be turned off altogether, but as of today, it still works.

**Comment by abidawson** [comment]
@randyzwitch Thanks for the swift reply, makes sense and will submit a PR if I'm able to take a closer look at some point.
@slin30 This version worked for me, thanks so much for the workaround!
