### ISSUE TITLE
Unable to connect to SiteCatalyst API

### ISSUE THREAD

**Issue by smach** [randyzwitch/RSiteCatalyst#36]
Thought I'd mention it in case it's a change in the SiteCatalyst API that broke something here. At first I thought I might have been shut off despite the end of token limits because I was pulling a lot of data today :-) but I have another login at one of our sister companies with a separate account and that's not working either. Perhaps my IP got blocked due to heavy activity this evening. Or maybe it's just a temporary problem with the SiteCatalyst API. But I'm getting this error no matter what I try to do and figured I'd let you know just in case. 

Error in file(con, "r") : cannot open the connection

**Comment by vivek0008** [comment]
Hi Randy,

Hope you are doing well.

I am using Omniture Rsitecatalyst API to fetch content the content through Rscript.

My script is working properly and i am getting data but from last 2 days when i tried to run the script i am getting an error. Which is "**Error in ApiRequest(body = report.description, func.name = "Report.Validate") : 
  ERROR: Bad Request  -  You do not have privileges to perform this operation."**

I do not why i am getting this. Please help me out in this.

**Comment by nagarjun1994** [comment]
Hi vivek,

I am facing the exact same problem you did.

Were you by chance able to solve it  ?

Would be great if you can share it here.

Thanks.

**Comment by TruTCTC** [comment]
@smach how did you solve this issue? I'm experiencing the same issue. Could you shed some light for me? Thank you!!

**Comment by smach** [comment]
@TruTCTC As far as I remember, it wasn't working for awhile and then it just started again. I don't think I did anything to fix it, it eventually fixed itself.

**Comment by TruTCTC** [comment]
Thank you so much! I’ll try tomorrow again to see if it works.:)

**Comment by TruTCTC** [comment]
Hi @smach, so I asked the community manager of Adobe Analytics forum, and he helped me solved the problem and I wanted to share here in case someone also encounters this issue in the future. 

Basically the admin needs to check 2 things under User Management. There are two places the user needs to have permissions:

1. Report Suite Tools > Customize > Ensure each of the Web Services check boxes are checked
2. Analytics Tools > Customize > Tools > Web Service Access checkbox is checked (there are multiple web services checkboxes in here, ensure the one under tools is checked).

Double check with your admin to ensure those are checked. Beyond that, customer care is likely going to be the next best point of contact. If you can give them an example request that's working, and another example of what's not working, they should be able to pinpoint the issue fairly easily.
