### ISSUE TITLE
Add back functionality for QueueRanked breakdown to return more than 10 results

### ISSUE THREAD

**Issue by randyzwitch** [randyzwitch/RSiteCatalyst#86]
Claire reports:

In the version of 1.3.3, when I was using the QueueRanked function with two elements, the search, top, and select option is just for the first element. And for the second element, it will return the top 1000000 lines. But now in the new version, only top 10 will be returned… How could I get all lines as before?

RZ: Add back this functionality. This used to be hardcoded in 1.3.3 at 1MM lines, to return seemingly everything that would come back in the breakdown portion.

**Comment by tfindlay-au** [comment]
Hello Randy,

Would you consider reviewing this to allow the 50000 limit to be overridden ?

Possibly made "top" accept a vector. If one value supplied apply to first element, if 2 apply to second etc.

Our use case is one where we may want top 10 pages by a selected list of authors, the limit of 50000 means we get every article for each author which is a bit annoying.

Cheers,
Tim.

**Comment by randyzwitch** [comment]
Can you create a new issue? It's hard to track when closed issues reach
this far back

**Comment by tfindlay-au** [comment]
Hello Randy,


Sorry about the delay, issue #146 created.


In other news, we have had some trouble with Adobe rejecting report definitions at times. Using debug mode, shows it calling the Report.Validate method, and failing with errors that the element or metric does not exist. To work around this, I used a tryCatch() block to immediately re-submit the same request and found it works.


We raised a support ticket with Adobe and speaking with one of their engineers, he suggested it was artificial, and rejecting validation when their servers were busy. He suggested we skip validation if we know the report definition is correct and just submit it to queue.


So I took a fork of your repo and made a small hack for QueueRanked() to skip validation (if specified). I've found this to work much faster and without throwing exceptions for validation. I'm not sure if you want to include this functionality in the project, but if so, you can pull the changes from my fork.


I'm not a very good developer, but if there is anything else I can do to help with RSiteCatalyst, let me know.


Thanks,

Tim.


________________________________
